import SHA

# resolved from this file's own location so it points at ReferenceTests/refimage_updates.txt
# even when this file is `include`d into ReferenceUpdater rather than ReferenceTests.
refimage_manifest_path() = normpath(joinpath(@__DIR__, "..", "refimage_updates.txt"))

struct RefimageUpdate
    path::String
    pin::String
end

reference_hash(file::AbstractString) = bytes2hex(SHA.sha256(read(file)))

function pin_for(path::AbstractString, reference_folder::AbstractString)
    ref = joinpath(reference_folder, path)
    return isfile(ref) ? reference_hash(ref) : "new"
end

function read_manifest(path::AbstractString = refimage_manifest_path())
    entries = RefimageUpdate[]
    isfile(path) || return entries
    for line in eachline(path)
        stripped = strip(line)
        (isempty(stripped) || startswith(stripped, "#")) && continue
        parts = split(stripped, '\t')
        length(parts) == 2 || error("Malformed manifest line (expected `path<TAB>pin`): $(repr(line))")
        push!(entries, RefimageUpdate(String(strip(parts[1])), String(strip(parts[2]))))
    end
    return entries
end

function deduplicate_by_path(entries)
    by_path = Dict{String, RefimageUpdate}()
    for e in entries
        by_path[e.path] = e
    end
    return sort!(collect(values(by_path)), by = e -> e.path)
end

const MANIFEST_HEADER = """
# Reference image update manifest. One entry per line: <Backend>/<name>.png<TAB><pin>
# pin is `new` (no stored reference yet), `delete` (remove on promotion), or the
# sha256 hex of the stored reference this update replaces.
# Generated by ReferenceUpdater, do not edit by hand. See ReferenceUpdater/README.md.
"""

function write_manifest(entries, path::AbstractString = refimage_manifest_path())
    open(path, "w") do io
        print(io, MANIFEST_HEADER)
        for e in deduplicate_by_path(entries)
            println(io, e.path, '\t', e.pin)
        end
    end
    return path
end

function classify_entries(entries, reference_folder::AbstractString)
    exempt_changed = Set{String}()
    exempt_new = Set{String}()
    to_delete = Set{String}()
    inert = RefimageUpdate[]
    for e in entries
        ref = joinpath(reference_folder, e.path)
        if e.pin == "new"
            isfile(ref) ? push!(inert, e) : push!(exempt_new, e.path)
        elseif e.pin == "delete"
            isfile(ref) ? push!(to_delete, e.path) : push!(inert, e)
        else
            (isfile(ref) && reference_hash(ref) == e.pin) ? push!(exempt_changed, e.path) : push!(inert, e)
        end
    end
    return (; exempt_changed, exempt_new, to_delete, inert)
end

function prune_inert(entries, reference_folder::AbstractString)
    inert_paths = Set(e.path for e in classify_entries(entries, reference_folder).inert)
    return filter(e -> !(e.path in inert_paths), entries)
end
