#=
## Notes on resolve/dirty state:

Dirty state is encoded in edges. Nodes only hold on to dirty state temporarily
in resolve!() while passing on state to dependents.

mark_dirty!() sets edge state to dirty, traveling down the the graph. If an
edge is marked dirty, all its dependents are also marked dirty.

resolve!() sets edge state to not dirty (resolved). Edges are selected by
traveling up the graph, but state is still updated top to bottom because we
need to resolve parent computations before a dependent computation can resolve.

Assuming resolve!() and mark_dirty!() do not run at the same time (and the
initial state is appropriate), an edge being dirty implies that all of its
dependents are dirty. Equivalently, an edge being resolved implies that all its
parents are resolved. Thus:
- mark_dirty!() may stop propagating down if an edge is marked dirty
- resolve!() may stop propagating up if an edge is marked resolved
Note that mark_resolved!() and unsafe_init!() (and whatever else may affect
resolved/dirty state) must keep state consistent with the rule(s) above to allow
early exits in mark_dirty!() and resolve!() (and themselves).


## Notes on concurrency

There are a lot of problems to find not just with asynchronous graph
interactions, many of which are probed by the concurrency tests.

As mentioned above, `mark_dirty!()`, `resolve!()` and other functions affecting
dirty state are not allowed to change that state at the same time. Consider a
graph `a -> b -> c` as an example:
- resolve!(c) walks up too a, resolves a, marks a resolved
- mark_dirty!(a) interjects and marks a, b, c as dirty (or just a if it exits early)
- resolve!(c) continues, marking b, c resolved
We now have broken the rules from above as `a` is marked dirty but its dependent
`b` is not.

A node in the graph can be an input to multiple edges. To keep the results of
these edges consistent, the value of the node is not allowed to change between
them. This means no direct updating of that node (i.e. no setindex!(),
setproperty!(), update!()) and no re-resolve!() of the parent edge (which may
have updated inputs) is allowed.

Note that users could (technically) try to update a node in the callback of an
edge. In that case the value setting function as well as mark dirty run within
the same Task, so ReentrantLock will not block the execution. This may lead to
corrupt state or desynchronized data with ReentrantLock, or deadlocks with a
more aggressive lock. Note as well that edge locks are likely to lock multiple
times since one edge may be the parent of multiple other edges.

Note that Observable outputs can further complicate this. Without them, one node
value and the states of a subset of edges update.¹ With them, update also needs
to queue an observable update, which requires a resolve itself. While the node
may already be freed by the original resolve, the observable-based resolve may
also target nodes that the original resolve still owns.

¹ Updating state can be a non-issue here. At the start of resolve, we can go
through all the involved edges, copy their "dirty" state to a new resolve state
variable and mark their normal state as "resolved", under exclusion of
mark_dirty!(). We can then base decision on the resolve state variable during
edge resolve while mark_dirty!() can already update state for the next resolve!().

Some general notes:
- Per graph locks are also complicated, because multiple graphs can be connected.
  resolve!() could try locking child_graph, then parent_graph, while update
  functions may try to lock parent_graph, then child_graph (deadlock potential)
- Graphs may also connect circularly, e.g. graph1.x -> graph2.x,
  graph2.y -> graph1.y. So graph relationships may loop, while the underlying
  edges don't
- update!() promises to update all variables in sync, i.e. in such a way that
  resolve!() either uses all the values from before update!() or all the values
  from after. This means update!() must wait for all the variables to be
  accessible.
=#

module ComputePipeline

using Preferences

const ENABLE_COMPUTE_CHECKS = @load_preference("ENABLE_COMPUTE_CHECKS", false)

enable_debugging!() = set_debug!(true)
disable_debugging!() = set_debug!(false)
function set_debug!(value::Bool)
    if value != ENABLE_COMPUTE_CHECKS
        @set_preferences!("ENABLE_COMPUTE_CHECKS" => value)
        @info "Changing the debug mode requires restarting Julia to take effect!"
    end
    return
end

using Observables

using Base: RefValue, tail

# include("KeyedReentrantLock.jl")
include("ResolveLock.jl")
include("nesting.jl")

const GLOBAL_LOCK = YieldingSpinLock()

deref(r::RefValue) = r[]
deref(x) = x

abstract type AbstractEdge end

"""
    struct Computed

A `Computed` represents a node in the `ComputeGraph`. It should not be created
directly but be generated by [`add_input!`](@ref) or [`register_computation!`](@ref).

A `Computed` can be accessed from the graph by `graph[:name]` where `:name` is
the name the node was created with. Its value is returned by `graph[:name][]`
which also runs any pending updates.
"""
mutable struct Computed
    name::Symbol
    # if a parent edge got resolved and updated this computed, dirty is temporarily true
    # so that the edges dependents can update their inputs accordingly
    dirty::Bool

    value::RefValue
    parent::AbstractEdge
    parent_idx::Int # index of parent.outputs this value refers to
    Computed(name) = new(name, false)
    function Computed(name, value::RefValue)
        validate_node_value(value)
        return new(name, false, value)
    end
    function Computed(name, value::RefValue, parent::AbstractEdge, idx::Integer)
        validate_node_value(value)
        return new(name, false, value, parent, idx)
    end
    function Computed(name, edge::AbstractEdge, idx::Integer)
        p = new(name, false)
        p.parent = edge
        p.parent_idx = idx
        return p
    end
end

hasparent(computed::Computed) = isdefined(computed, :parent)
getparent(computed::Computed) = hasparent(computed) ? computed.parent : nothing
function Base.eltype(computed::Computed)
    isdefined(computed, :value) || computed[]
    return eltype(computed.value)
end

struct ResolveException{E <: Exception} <: Exception
    start::Computed
    error::E
end

struct TypedEdge{InputTuple, OutputTuple, F}
    callback::F
    inputs::InputTuple
    inputs_dirty::Vector{Bool}
    outputs::OutputTuple
    output_nodes::Vector{Computed}
end

"""
    struct ComputeEdge

A `ComputeEdge` represents the computation connecting one set of nodes to another.
They are considered internal and should not be interacted with or created directly.
"""
struct ComputeEdge{T} <: AbstractEdge
    graph::T
    callback::Function

    inputs::Vector{Computed}
    inputs_dirty::Vector{Bool}

    outputs::Vector{Computed}
    should_resolve_now::RefValue{Bool}
    dirty::RefValue{Bool}
    lock::ResolveLock

    # edges, that rely on outputs from this edge
    # Mainly needed for mark_dirty!(edge) to propagate to all dependents
    dependents::Vector{ComputeEdge{T}}
    typed_edge::RefValue{TypedEdge}
end

function ComputeEdge(f, graph::T, input::Computed, output::Computed) where {T}
    return ComputeEdge{ComputeGraph}(
        graph, f, [input], [true], [output],
        Ref(false), Ref(true), ResolveLock(),
        ComputeEdge[], RefValue{TypedEdge}()
    )
end

function _get_named_change(::NamedTuple{Names}, dirty) where {Names}
    values = ntuple(i -> dirty[i], length(Names))
    return NamedTuple{Names, NTuple{length(Names), Bool}}(values)
end

function TypedEdge(edge::ComputeEdge)
    N = length(edge.inputs)
    names = ntuple(i -> edge.inputs[i].name, N)
    values = ntuple(i -> edge.inputs[i].value, N)
    inputs = NamedTuple{names}(values)
    # force `callback` and `inputs` types to be inferred so the rest of the
    # constructor can be type stable
    return Base.invokelatest(TypedEdge, edge, edge.callback, inputs)
end

function TypedEdge(edge::ComputeEdge, f, inputs)
    dirty = _get_named_change(inputs, edge.inputs_dirty)

    result = f(map(getindex, inputs), dirty, nothing)

    if result isa Tuple

        if !all(is_node_value_valid, result)
            invalid_results = [output.name => value for (output, value) in zip(edge.outputs, result) if !is_node_value_valid(value)]
            strings = map(kv -> "$(kv[1]) = ::$(typeof(kv[2]))", invalid_results)
            str = join(strings, ", ")
            error("Edge callback returned invalid types for outputs: [$str]")
        end

        if length(result) != length(edge.outputs)
            m = first(methods(edge.callback))
            line = string(m.file, ":", m.line)
            error("Result needs to have same length. Found: $(result), for func $(line)")
        end

        outputs = ntuple(length(result)) do i
            v = result[i] isa RefValue ? result[i] : RefValue(result[i])
            if isdefined(edge.outputs[i], :value)
                edge.outputs[i].value[] = v[] # set value of existing node
            else
                edge.outputs[i].value = v # initialize to fully typed RefValue
            end
            return edge.outputs[i].value
        end
        foreach(node -> node.dirty = true, edge.outputs)

    elseif isnothing(result)

        outputs = ntuple(length(edge.outputs)) do i
            if isdefined(edge.outputs[i], :value)
                edge.outputs[i].value[] = nothing
            else
                edge.outputs[i].value = RefValue(nothing)
            end
            return edge.outputs[i].value
        end
        foreach(node -> node.dirty = false, edge.outputs)

    else
        error("Wrong type as result $(typeof(result)). Needs to be Tuple with one element per output or nothing. Value: $result")
    end
    return TypedEdge(f, inputs, edge.inputs_dirty, outputs, edge.outputs)
end


"""
    struct Input

A `Input` represents an entry point to the `ComputeGraph`. Like [`Computed`](@ref)
it should not be created directly, but rely on [`add_input!`](@ref). It should
be updated by `update!(graph, input_name = new_value)` to correctly update the
state of the compute graph.
"""
mutable struct Input{T} <: AbstractEdge
    graph::T
    name::Symbol
    value::Any
    f::Any
    output::Computed
    should_resolve_now::Bool
    dirty::Bool
    input_lock::YieldingSpinLock
    lock::ResolveLock
    dependents::Vector{ComputeEdge{T}}
    force_update::Bool
end

Base.setproperty!(::Input, ::Symbol, ::Observable) = error("Setting the value of an ::Input to an Observable is not allowed")
Base.setproperty!(::Input, ::Symbol, ::Computed) = error("Setting the value of an ::Input to a Computed is not allowed")

function Input(graph, name, value, f, output, force_update = false)
    validate_node_value(value)
    return Input{ComputeGraph}(
        graph, name, value, f, output, false, true,
        YieldingSpinLock(), ResolveLock(),
        ComputeEdge[], force_update
    )
end

abstract type AbstractComputeGraph end

"""
    ComputeGraph()

Creates a new empty `ComputeGraph`.

Inputs can be added to the graph using [`add_input`](@ref). Computations and the
connected outputs can be added with [`register_computation!`](@ref).

To update an input, `update!(graph, input_name = new_value)` can be used. To get
an up-to-date value from an output use `graph[:output_name][]`.

## Example:

```
graph = ComputeGraph()

add_input!(graph, :first_node, 1)
register_computation!(graph, [:first_node], [:derived_node]) do inputs, changed, cached
    return (2 * inputs[1][], )
end

update!(graph, first_node = 2)
graph[:derived_node][]
```
"""
struct ComputeGraph <: AbstractComputeGraph
    inputs::Dict{Symbol, Input}
    outputs::Dict{Symbol, Computed}
    nesting::NestedSearchTree
    onchange::Observable{Set{Symbol}}
    obs_to_notify::Set{Symbol}
    observables::Dict{Symbol, Observable}
    should_deepcopy::Set{Symbol}
    observerfunctions::Vector{Observables.ObserverFunction}
    onchange_obs_to_update::Vector{Observable}
end

validate_node_value(x) = nothing
validate_node_value(x::RefValue) = isassigned(x) ? validate_node_value(x[]) : nothing
# shouldn't have those in input.value or computed.value[]
function validate_node_value(::Union{T, RefValue{T}}) where {T <: Union{Computed, Input, ComputeGraph, ComputeEdge}}
    error("The value of a compute node is not allowed to be of type ::$T.")
end

is_node_value_valid(x) = true
is_node_value_valid(x::RefValue) = isassigned(x) ? is_node_value_valid(x[]) : true
# shouldn't have those in input.value or computed.value[]
function is_node_value_valid(::Union{T, RefValue{T}}) where {T <: Union{Computed, Input, ComputeGraph, ComputeEdge}}
    return false
end

"""
    get_observable!(graph::ComputeGraph, key::Symbol[; use_deepcopy = true])

Returns an observable which contains the up to date value of the graph node with name `key`.

Note that in order for the Observable to be up to date, the respective node needs
to resolve immediately after being marked dirty. This may cause the graph to
update more frequently.

Within the compute graph, data can be updated in-place by using cached values.
This makes it impossible for the compute graph to know whether that data has
changed as the old data is not available anymore. In these cases updates are
always propagated and observables are always triggered. If the observable is
used to (eventually) update an input of the node it represents, this could lead
to infinite loops of equal updates. To prevent these, the data in the Observable
is a `deepcopy` of the data in the compute node and their data is compared
before updating.
Setting `use_deepcopy = false` will turn this safeguard off, removing both the
deepcopy and the equality check. In this case in-place updates of the node will
always trigger observable updates. Any other duplicate updates will be skipped.
"""
function get_observable!(attr::ComputeGraph, key::Symbol; use_deepcopy = true)
    # Because we allow output arrays to be reused it can be impossible to tell
    # if the data has updated. In this case the data is marked as dirty/changed
    # and added to the `onchange`. If this data is fed into an Observable which
    # updates the graph it can lead to infinite loops.
    # To prevent this we have to disambiguate the data and do == checks here.
    # This requires us to copy data every time we update and we can't use
    # `copy` because that is not always available (e.g. not for Rect)
    return get!(attr.observables, key) do
        if use_deepcopy
            push!(attr.should_deepcopy, key)
        end
        # resolve first so eltype can work
        val = attr.outputs[key]
        initial_value = use_deepcopy ? deepcopy(val[]) : val[]
        # The graph already does ignore_equal_values = true checks when data is
        # not updated in-place, so it's useless to add it here
        return Observable{eltype(val.value)}(initial_value)
    end
end

function get_observable!(c::Computed; use_deepcopy = true)
    if hasparent(c)
        p = getparent(c)
        return get_observable!(p.graph, c.name; use_deepcopy = use_deepcopy)
    else
        error("Cannot get observable for Computed without parent")
    end
end

# ComputeEdge(f) = ComputeEdge(f, Computed[])
function ComputeEdge(f, graph::ComputeGraph, inputs::Vector{Computed})
    return ComputeEdge{ComputeGraph}(
        graph, f, inputs, fill(true, length(inputs)), Computed[],
        Ref(false), Ref(true), ResolveLock(),
        ComputeEdge[], RefValue{TypedEdge}()
    )
end

function ComputeGraph()
    graph = ComputeGraph(
        Dict{Symbol, Input}(), Dict{Symbol, Computed}(),
        NestedSearchTree(),
        Observable(Set{Symbol}()), Set{Symbol}(),
        Dict{Symbol, Observable}(), Set{Symbol}(),
        Observables.ObserverFunction[], Observable[]
    )

    on(graph.onchange) do changeset
        # Remove node names not backed by observables
        intersect!(changeset, keys(graph.observables))

        obs_to_notify = graph.obs_to_notify

        # update values without triggering observables and add all updated names
        # to obs_to_notify
        for key in changeset
            # Still necessary?
            haskey(graph.observables, key) || continue

            val = graph.outputs[key][]
            obs = graph.observables[key]
            # Trust the graph to discard equal values. This doesn't work for
            # anything updated in-place
            if !(key in graph.should_deepcopy)
                obs.val = val
                push!(obs_to_notify, key)
            elseif val != obs[] # treat in-place updates
                obs.val = deepcopy(val)
                push!(obs_to_notify, key)
            else # same value (with deepcopy), skip update
                # delete!(changeset, key)
            end
        end

        # Clear the changeset now so that if notify causes the graph to update
        # again, the already processed names are not processed again.
        empty!(changeset)

        # trigger observables from obs_to_notify.
        # Separating this from changeset allows notify to cause another
        # on(onchange) to trigger without issues.
        # - value setting & empty!(changeset) doesn't delete from obs_to_notify
        # - the inner on(onchange) adds to the obs_to_notify Set, so no notifies
        #   don't duplicate
        while !isempty(obs_to_notify)
            key = pop!(obs_to_notify)
            notify(graph.observables[key])
        end

        return Consume(false)
    end

    return graph
end

_first_arg(args, changed, last) = (args[1],)

"""
    alias!(graph::ComputeGraph, input::Symbol, output::Symbol)

Creates `output` as an alias of `input`.
"""
function alias!(attr::ComputeGraph, key::Symbol, alias_key::Symbol)
    # TODO: more efficient implementation!
    register_computation!(_first_arg, attr, [key], [alias_key])
    return attr
end

function isdirty(computed::Computed)
    return hasparent(computed) && isdirty(computed.parent)
end


isdirty(edge::ComputeEdge) = edge.dirty[]

"""
    mark_resolved!(computed)

Mark the parent edge of a compute node as resolved, so that the node will no
longer try to update. This will be undone the next time any (recursive) input
to the node is updated.
"""
function mark_resolved!(computed::Computed)
    if hasparent(computed)
        try
            mark_resolved!(computed.parent)
        catch e
            rethrow(ResolveException(computed, e))
        end
    end
    return
end
function mark_resolved!(edge::ComputeEdge)
    if edge.dirty[]
        key = lock_before_resolve!(edge)
        try
            try_resolve_parents(edge, key)
            edge.should_resolve_now[] = false
            fill!(edge.inputs_dirty, false)
        finally
            foreach(e -> unlock_input!(e, key), edge.inputs)
            unlock(edge.lock, key)
        end
    end
    return
end
mark_resolved!(edge::Input) = edge.dirty = false

function mark_dirty!(computed::Computed)
    if hasparent(computed)
        mark_dirty!(computed, computed.parent.graph.onchange_obs_to_update)
    end
    return
end
function mark_dirty!(computed::Computed, obs_to_update)
    if hasparent(computed)
        @lock GLOBAL_LOCK begin
            locked_mark_dirty!(computed, obs_to_update)
        end
    end
    return
end

mark_dirty!(x::AbstractEdge) = mark_dirty!(x, x.graph.onchange_obs_to_update)
function mark_dirty!(x, onchange_obs_to_update)
    # lock_before_resolve!() is not allowed to run while mark_dirty!() runs
    # lock GLOBAL_LOCK to prevent it
    @lock GLOBAL_LOCK locked_mark_dirty!(x, onchange_obs_to_update)
end

locked_mark_dirty!(x::Computed) = locked_mark_dirty!(x, x.parent.graph.onchange_obs_to_update)
locked_mark_dirty!(e::AbstractEdge) = locked_mark_dirty!(e, e.graph.onchange_obs_to_update)
function locked_mark_dirty!(computed::Computed, obs_to_update)
    if hasparent(computed)
        parent = computed.parent
        @lock computed.parent.lock begin
            computed.dirty = true
        end
        # TODO: Can we avoid marking the parent dirty?
        # Note: Without the parent running computed.dirty doesn't get
        # transferred to dependents in resolve!().
        # TODO: Isn't writing to dirty risky without locking the edge?
        # TODO: Can this be called from the same callstack as resolve!(),
        # causing lock(edge.lock) to not block?
        locked_mark_dirty!(parent, obs_to_update)

        # push!(parent.graph.onchange.val, computed.name)
        # if !(parent.graph.onchange in obs_to_update)
        #     push!(obs_to_update, parent.graph.onchange)
        # end
        # for dependent in parent.dependents
        #     locked_mark_dirty!(dependent, obs_to_update)
        # end

        # @lock parent.lock begin
        #     computed.dirty = true
        #     for dependent in parent.dependents
        #         @lock dependent.lock begin
        #             mark_input_dirty!(computed.parent, dependent)
        #         end
        #     end
        #     computed.dirty = false
        # end
    end
    return
end

function locked_mark_dirty!(edge::ComputeEdge, onchange_obs_to_update::Vector{Observable})
    if !edge.dirty[]
        # Assumes this is the same graph as edge.outputs (for parent -> child graph edges)
        g = edge.graph
        for output in edge.outputs
            push!(g.onchange.val, output.name)
            g.onchange in onchange_obs_to_update || push!(onchange_obs_to_update, g.onchange)
        end

        edge.dirty[] = true
        for dep in edge.dependents
            locked_mark_dirty!(dep, onchange_obs_to_update)
        end
    end
    return
end

function locked_mark_dirty!(input::Input, onchange_obs_to_update::Vector{Observable})
    if !input.dirty
        push!(input.graph.onchange.val, input.name)
        if !(input.graph.onchange in onchange_obs_to_update)
            push!(onchange_obs_to_update, input.graph.onchange)
        end

        input.dirty = true
        for edge in input.dependents
            locked_mark_dirty!(edge, onchange_obs_to_update)
        end
    end
    return
end

update_observables!(comp::Computed) = update_observables!(comp.parent)
update_observables!(edge::Input) = update_observables!(edge.graph)
update_observables!(edge::ComputeEdge) = update_observables!(edge.graph)
update_observables!(graph::ComputeGraph) = update_observables!(graph.onchange_obs_to_update)
function update_observables!(onchange_obs_to_update::Vector{Observable})
    foreach(notify, onchange_obs_to_update)
    empty!(onchange_obs_to_update)
    return
end

function Base.setindex!(computed::Computed, value)
    if computed.parent isa Input
        return setindex!(computed.parent, value)
    elseif hasparent(computed)
        @lock GLOBAL_LOCK begin
            @lock computed.parent.lock begin
                computed.value[] = value
            end
            # we don't need to keep the edge locked, but we do need to prevent
            # lock_before_resolve!() from running, so keep the GLOBAL_LOCK locked
            locked_mark_dirty!(computed)
        end
        # TODO: Does this need to be locked too?
        update_observables!(computed)
        return value
    else
        computed.value[] = value
        return value
    end
end

function Base.setindex!(input::Input, value)
    _update_input!(input, value)
    return value
end

function Base.setproperty!(attr::ComputeGraph, key::Symbol, value)
    _update_input!(attr.inputs[key], value)
    return value
end

function _update_input!(input::Input, value)
    force_update = input.force_update
    if !force_update && is_same(input.value, value)
        return value
    end
    # GLOBAL_LOCK needs to be locked to prevent dirty state from changing during
    # lock_before_resolve!()
    # input.input_lock needs to be locked to prevent updating data currently
    # used in the input callback (during resolve!())
    @lock GLOBAL_LOCK begin
        @lock input.input_lock begin
            input.value = value
        end
        locked_mark_dirty!(input)
    end
    update_observables!(input)
    return value
end

function locked_update_input!(input::Input, value)
    force_update = input.force_update
    if !force_update && is_same(input.value, value)
        return value
    end
    input.value = value
    locked_mark_dirty!(input)
    return value
end

"""
    update!(graph; kwargs...)
    update!(graph, pairs::Pair{Symbol, Any}...)

Updates any number of inputs in the graph based on the passed `key = value`
keyword arguments. The `key` refers to the name of the input and the `value` is
the new value.

## Example:

```
graph = ComputeGraph()
add_input!(graph, :first_node, 1)
update!(graph, first_node = 2)
update!(graph, :first_node => 2)
```
"""
update!(attr::AbstractComputeGraph; kwargs...) = update!(attr, [Pair{Symbol, Any}(k, v) for (k, v) in kwargs])
update!(attr::AbstractComputeGraph, dict::Dict) = _update!(attr, dict)
update!(attr::AbstractComputeGraph, pairs::Pair...) = _update!(attr, [Pair(k, v) for (k, v) in pairs])
update!(attr::AbstractComputeGraph, pairs::AbstractVector{<:Pair}) = _update!(attr, pairs)

function _update!(attr::ComputeGraph, pairs)
    # Checks first so we don't wait on locks just to error
    keys = [merged_key(keylike) for (keylike, _) in pairs]
    for k in keys
        haskey(attr.inputs, k) || error("Attribute $k not found in ComputeGraph")
    end

    # don't allow lock_before_resolve!() to acquire input locks until we have
    # acquired all the onces we will update
    @lock GLOBAL_LOCK begin
        # make sure resolve!() isn't still using the inputs we update here
        # Note: resolve will always have input.lock locked when it locks
        # input.input_lock, so it is sufficient to lock input.lock. (Competing writes
        # are not our concern here)
        for key in keys
            lock(attr.inputs[key].lock)
        end
    end

    try
        # update
        for (key, (_, value)) in zip(keys, pairs)
            locked_update_input!(attr.inputs[key], value)
        end
    finally
        for key in keys
            unlock(attr.inputs[key].lock)
        end
    end

    update_observables!(attr)
    return attr
end

function Base.haskey(attr::ComputeGraph, key::Symbol)
    return haskey(attr.outputs, key) || haskey(attr.nesting.keytables[1], key)
end
function Base.haskey(graph::ComputeGraph, key::Symbol, keys::Symbol...)
    return haskey(graph.nesting, key, keys...)
end
function Base.haskey(graph::ComputeGraph, keys::Tuple{Vararg{Symbol}})
    return haskey(graph, keys...)
end

Base.get(attr::ComputeGraph, key::Symbol, default) = get(attr.outputs, key, default)
Base.keys(graph::ComputeGraph) = keys(graph.outputs)

function Base.getproperty(attr::ComputeGraph, key::Symbol)
    # more efficient to hardcode?
    key === :inputs && return getfield(attr, :inputs)
    key === :outputs && return getfield(attr, :outputs)
    key === :nesting && return getfield(attr, :nesting)
    key === :onchange && return getfield(attr, :onchange)
    key === :obs_to_notify && return getfield(attr, :obs_to_notify)
    key === :observables && return getfield(attr, :observables)
    key === :observerfunctions && return getfield(attr, :observerfunctions)
    key === :onchange_obs_to_update && return getfield(attr, :onchange_obs_to_update)
    key === :lock && return getfield(attr, :lock)
    key === :should_deepcopy && return getfield(attr, :should_deepcopy)
    return attr[key]
end

"""
    struct ComputeGraphView

A `ComputeGraphView` represents a nested ComputedGraph. It is returned when
accessing the parent of a nested node within a ComputeGraph.
"""
struct ComputeGraphView <: AbstractComputeGraph
    parent::ComputeGraph
    nested_trace::TemporarySearchResult
end

"""
    ComputeGraphView(parent, key::Symbol)

Manually creates a view into a ComputeGraph.
"""
function ComputeGraphView(parent::ComputeGraph, key::Symbol)
    if !haskey(parent, key)
        add_path!(parent.nesting, key)
    end
    return parent[key]
end

function ComputeGraphView(view::ComputeGraphView, key::Symbol)
    if !haskey(view, key)
        add_key!(
            root(view).nesting,
            view.nested_trace.next_index,
            (key,), false
        )
    end
    return view[key]
end

root(g::ComputeGraph) = g
root(v::ComputeGraphView) = v.parent

function Base.show(io::IO, view::ComputeGraphView)
    trace = view.nested_trace
    level_dict = trace.parent.keytables[trace.next_index]
    _show_view_from_table(io, level_dict)
    return
end

function _show_view_from_table(io::IO, level_dict::Dict)
    ks = collect(keys(level_dict))
    kstr = if length(ks) > 5
        ":$(ks[1]), :$(ks[2]), :$(ks[3]),..."
    else
        join(Ref(':') .* string.(ks), ", ")
    end
    print(io, "ComputeGraphView($kstr)")
    return
end

function Base.show(io::IO, ::MIME"text/plain", view::ComputeGraphView)
    attr = view.parent
    trace = view.nested_trace

    level = trace.next_index
    level_dict = trace.parent.keytables[level]
    base_key = merged_key(trace)

    print(io, "Nested view of ComputeGraph at graph.$base_key containing:")
    for (key, val) in level_dict
        full_key = Symbol(base_key, :(.), key)
        if val == -1
            node = get(attr.inputs, full_key, attr.outputs[full_key])
            print(io, "\n  ", key, " => ", node)
        else
            next_level_dict = trace.parent.keytables[val]
            print(io, "\n  ", key, " => ")
            _show_view_from_table(io, next_level_dict)
        end
    end

    return
end

Base.keys(view::ComputeGraphView) = keys(view.nested_trace)
recursive_keys(view::ComputeGraphView) = recursive_keys(view.nested_trace)

Base.haskey(view::ComputeGraphView, keys::Symbol...) = haskey(view.nested_trace, keys...)
Base.haskey(view::ComputeGraphView, keys::Tuple{Vararg{Symbol}}) = haskey(view.nested_trace, keys...)

# Generates pairs for `foo(; kwargs...)`
function Base.iterate(view::ComputeGraphView)
    ks = keys(view)
    return iterate(view, (ks, iterate(ks)))
end

function Base.iterate(view::ComputeGraphView, state)
    ks, substate = state
    if isnothing(substate)
        return nothing
    else
        key, key_state = substate
        return key => view[key], (ks, iterate(ks, key_state))
    end
end

function Base.length(view::ComputeGraphView)
    trace = view.nested_trace
    level = trace.next_index
    return length(trace.parent.keytables[level])
end

Base.eltype(::Type{ComputeGraphView}) = Union{Pair{Symbol, ComputeGraphView}, Pair{Symbol, Computed}}

# only collects outputs as those are useful to create a child graph
# TODO: these don't really fit together
# Base.pairs(graph::ComputeGraph) = graph.outputs # not nested
Base.pairs(view::ComputeGraphView) = (p for p in view) # nested

function Base.getindex(attr::ComputeGraph, key::Symbol)
    if haskey(attr.outputs, key)
        return attr.outputs[key]
    else
        temp_result = attr.nesting[key]
        return ComputeGraphView(attr, temp_result)
    end
end

function Base.propertynames(attr::ComputeGraphView)
    return collect(keys(attr.parent.nesting.keytables[attr.nested_trace.next_index]))
end
function Base.getproperty(attr::ComputeGraphView, key::Symbol)
    hasfield(ComputeGraphView, key) && return getfield(attr, key)
    return getindex(attr, key)
end

function Base.getindex(attr::AbstractComputeGraph, key1::Symbol, key2::Symbol, keys::Symbol...)
    return getindex(getindex(attr, key1), key2, keys...)
end

function Base.getindex(attr::ComputeGraphView, key::Symbol)
    temp_result = attr.nested_trace[key]
    if isfinal(temp_result)
        merged = merged_key(temp_result)
        return attr.parent.outputs[merged]
    else
        return ComputeGraphView(attr.parent, temp_result)
    end
end
# Compat for (graph.attributes[]::Attributes)[:entry]/.entry
Base.getindex(attr::ComputeGraphView) = attr

function Base.setproperty!(attr::ComputeGraphView, key::Symbol, value)
    temp_result = attr.nested_trace[key]
    merged = merged_key(temp_result)
    if isfinal(temp_result)
        setproperty!(attr.parent, merged, value)
    else
        error("Can't set $merged as it is an incomplete path to a compute node.")
    end
    return
end

function Base.setindex!(attr::ComputeGraphView, value, key1::Symbol, key2::Symbol, keys::Symbol...)
    return setindex!(getindex(attr, key1), value, key2, keys...)
end

function Base.setindex!(attr::ComputeGraphView, value, key::Symbol)
    temp_result = attr.nested_trace[key]
    if isfinal(temp_result)
        merged = merged_key(temp_result)
        return setindex!(attr.parent[merged], value)
    else
        error("Can't set $merged as it is an incomplete path to a compute node.")
    end
end

function _update!(view::ComputeGraphView, values)
    root = merged_key(view.nested_trace.keys)
    new_values = [Pair(merged_key(root, k), v) for (k, v) in values]
    return _update!(view.parent, new_values)
end

# function Base.setindex!(attr::AbstractComputeGraph, g::ComputeGraph, key::Symbol)
#     if !(isempty(g.inputs) && isempty(g.outputs))
#         error("graph[key] = ComputeGraph() is only allowed with empty ComputeGraphs")
#     end
#     return ComputeGraphView(attr, key)
# end

isdirty(input::Input) = input.dirty

Base.getindex(computed::Computed) = resolve!(computed)

################################################################################

# After resolving a parent edge, inform the dependent edge about the nodes the
# parent updated.
function mark_input_dirty!(parent::ComputeEdge, edge::ComputeEdge)
    @assert !parent.should_resolve_now[]
    for i in eachindex(edge.inputs)
        edge.inputs_dirty[i] |= getfield(edge.inputs[i], :dirty)
    end
    return
end

function mark_input_dirty!(parent::Input, edge::ComputeEdge)
    @assert !parent.should_resolve_now
    for i in eachindex(edge.inputs)
        edge.inputs_dirty[i] |= getfield(edge.inputs[i], :dirty)
    end
    return
end

function set_result!(edge::TypedEdge, result, i, value)
    if isnothing(value) || is_same(edge.outputs[i][], value)
        edge.output_nodes[i].dirty = false
    else
        edge.output_nodes[i].dirty = true
        edge.outputs[i][] = deref(value)
    end
    if !isempty(result)
        next_val = first(result)
        rem = Base.tail(result)
        set_result!(edge, rem, i + 1, next_val)
    end
    return
end

function set_result!(edge::TypedEdge, result)
    next_val = first(result)
    rem = Base.tail(result)
    return set_result!(edge, rem, 1, next_val)
end

is_same(@nospecialize(old), @nospecialize(new)) = false
is_same(old::Symbol, new::Symbol) = old == new
function is_same(old::T, new::T) where {T}
    if isbitstype(T)
        # We can compare immutable isbits type per value with `===`
        return old === new
    else
        # For mutable types, we can only compare them if they're not pointing to the same  object
        # If they are the same, we have to give up since we can't test if they got mutated in-between
        # Otherwise we can compare by equivalence
        same_object = old === new
        return same_object ? false : isequal(old, new)
    end
end

# do we want this type stable?
# This is how we could get a type stable callback body for resolve
function locked_resolve!(edge::TypedEdge)
    if any(edge.inputs_dirty) # only call if inputs changed
        dirty = _get_named_change(edge.inputs, edge.inputs_dirty)
        vals = map(getindex, edge.outputs)
        names = ntuple(length(vals)) do i
            edge.output_nodes[i].name
        end
        last = NamedTuple{names}(vals)
        result = edge.callback(map(getindex, edge.inputs), dirty, last)
        if result isa Tuple
            if length(result) != length(edge.outputs)
                error("Did not return correct length: $(length(result)) $result results into $(length(edge.outputs)) outputs, in $(edge.callback)")
            end
            set_result!(edge, result)
        elseif isnothing(result)
            foreach(x -> x.dirty = false, edge.output_nodes)
        else
            error("Needs to return a Tuple with one element per output, or nothing")
        end
    end
    return
end

function locked_resolve!(input::Input, ::UInt64)
    # See locked_resolve!(::ComputeEdge)
    if input.should_resolve_now
        try
            # Technically input.value could change while input.f runs if not
            # protected. It doesn't need to be kept alive for multiple resolve
            # accesses though, so a local lock should suffice.
            value = @lock input.input_lock begin
                input.f(input.value)
            end
            if isdefined(input.output, :value)
                input.output.value[] = deref(value)
            else
                input.output.value = value isa RefValue ? value : RefValue(value)
            end
        catch e
            input.dirty = true
            rethrow(e)
        finally
            input.should_resolve_now = false
            input.output.dirty = true
            for edge in input.dependents
                mark_input_dirty!(input, edge)
            end
            input.output.dirty = false
        end
    end
    return
end

function locked_resolve!(computed::Computed, lock_key)
    if hasparent(computed)
        locked_resolve!(computed.parent, lock_key)
    end
    return
end

function unlock_input!(c::Computed, lock_key)
    if hasparent(c)
        unlock_input!(c.parent, lock_key)
    end
    return
end

unlock_input!(e::AbstractEdge, lock_key) = unlock(e.lock, lock_key)


reset_resolve_state!(c::Computed, lock_key) = reset_resolve_state!(c.parent, lock_key)
function reset_resolve_state!(edge::Input, lock_key)
    if edge.should_resolve_now[]
        edge.dirty = true
        edge.should_resolve_now = false
    end
    unlock(edge.lock, lock_key)
    return
end

function reset_resolve_state!(edge::ComputeEdge, lock_key)
    if edge.should_resolve_now[]
        foreach(e -> reset_resolve_state!(e, lock_key), edge.inputs)
        edge.dirty[] = true
        edge.should_resolve_now[] = false
    end
    unlock(edge.lock, lock_key)
    return
end

function try_resolve_parents(edge::ComputeEdge, lock_key)
    idx = 1
    try
        # resolve parents, which updates our inputs_dirty
        while idx <= length(edge.inputs)
            locked_resolve!(edge.inputs[idx], lock_key)
            idx += 1
        end
    catch e
        # If one edge failed we need to unlock all of them and clean up state
        # for the ones after the failing one (idx+1..end)
        for i in eachindex(edge.inputs)
            if i <= idx # these cleanup up their state and just need an unlock
                unlock_input!(edge.inputs[i], lock_key)
            else # these did not run at all so they need unlock + state cleanup
                reset_resolve_state!(edge.inputs[i], lock_key)
            end
        end
        # clear our state
        edge.dirty[] = true
        edge.should_resolve_now[] = false
        # and rethrow
        rethrow(e)
    end
    return
end

function locked_resolve!(edge::ComputeEdge, lock_key)
    if edge.should_resolve_now[]
        try_resolve_parents(edge, lock_key)

        try
            # run the callback, which uses our inputs_dirty and sets outputs.dirty
            if !isassigned(edge.typed_edge)
                edge.typed_edge[] = TypedEdge(edge)
            else
                locked_resolve!(edge.typed_edge[])
            end
        catch e
            edge.dirty[] = true
            rethrow(e)
        finally
            # stop protecting the input values this node used (if multiple edges use
            # them they will be protected until all nodes stop protecting them)
            foreach(e -> unlock_input!(e, lock_key), edge.inputs)
            # prevent further visits to this node from running callbacks (for performance)
            edge.should_resolve_now[] = false
            # reset inputs_dirty for the next time the edge needs to resolve
            fill!(edge.inputs_dirty, false)
            # pass on the nodes changed by the callback to our dependents
            for dep in edge.dependents
                mark_input_dirty!(edge, dep)
            end
            # reset outputs.dirty for the next time the edge needs to resolve
            foreach(comp -> comp.dirty = false, edge.outputs)
        end
    end
    return
end

function resolve!(computed::Computed)
    if hasparent(computed)
        try
            resolve!(computed.parent)
        catch e
            rethrow(ResolveException(computed, e))
        end
    end
    return computed.value[]
end

function lock_before_resolve!(x)
    lock_key = generate_lock_key()
    # Prevent other instances of lock_before_resolve!() from competing over edge
    # locks. Also prevent mark_dirty!() from running during this, as changing
    # edge.dirty can cause a later hits of the same edge to lock when earlier
    # ones didn't.
    @lock GLOBAL_LOCK begin
        _lock_before_resolve!(x, lock_key)
    end
    return lock_key
end

function _lock_before_resolve!(edge::ComputeEdge, lock_key)
    # Lock every node that is dirty as well as their direct parents which carry
    # the inputs to this node. If this edge is reached multiple times, it itself
    # needs to be locked multiple times, but its parents don't. `locked_resolve!()`
    # will not recompute the edge after the its first resolve, so it won't use
    # the parents multiple times.
    lock(edge.lock, lock_key)
    if edge.dirty[] && !edge.should_resolve_now[]
        foreach(e -> _lock_before_resolve!(e, lock_key), edge.inputs)
        edge.should_resolve_now[] = true
        edge.dirty[] = false
    end
    return
end

function _lock_before_resolve!(edge::Input, lock_key)
    lock(edge.lock, lock_key)
    if edge.dirty && !edge.should_resolve_now
        edge.should_resolve_now = true
        edge.dirty = false
    end
    return
end

function _lock_before_resolve!(c::Computed, lock_key)
    # Not having a parent leaves the computed unprotected, which could cause
    # it to desync during resolve!()... TODO: Maybe error?
    if hasparent(c)
        _lock_before_resolve!(c.parent, lock_key)
    end
    return
end

function resolve!(edge::AbstractEdge)
    lock_key = lock_before_resolve!(edge)
    try
        locked_resolve!(edge, lock_key)
    finally
        # locks unlock in the dependents of an edge, so this one is still locked
        unlock(edge.lock, lock_key)
    end
    return
end


"""
    add_input!([callback], compute_graph, name::Symbol, value)
    add_input!([callback], compute_graph, names::Symbol..., value)
    add_input!([callback], compute_graph, names::Tuple, value)

Adds a new input to the given `compute_graph`. The input is referred to by the
given `name` and is initialized with the given `value`. If a `callback` is given
any new value will be passed to `callback(name, new_value)` before being stored
in the compute graph.

If multiple `names` are given either as a tuple or as multiple arguments, the
input is treated as a nested input. This means the node is accessed in a nested
fashion, e.g. `graph.a.b.c` with `add_input!(graph, :a, :b, :c, value)`. This
type of nesting can also occur by passing a nested view into the compute graph,
e.g. `add_input!(graph.a, :b, :c, value)`.

## Example:

```
graph = ComputeGraph()

add_input!(graph, :first_node, 1)
add_input!((k, v) -> Float32(v), graph, :second_node, 2)
add_input!(graph, (:outer, :inner), 1)
add_input!(graph.outer, :middle, :inner, 1)
```
"""
add_input!

# add_input!([func, ], attr, args...) handles multi-key -> tuple of keys
# add_input!([func, ], attr, tuple, val) handles nesting, creates single key
# add_input!([func, ], attr, key, val) handles value based processing
# _add_input!(func, attr, key, val) handles node insertion

# Since attr.input return the Computed node after the Input it's convenient to
# have this work with Computed
"""
    enable_forced_updates!(input)

Sets `input.forced_update = true` which makes the `Input` propagate same value
updates to the `Computed` node they connect to. To further propagate same
value updates through `ComputeEdge`s, wrap the values to propagate in
`ExplicitUpdate(value, :force)`.
"""
function enable_forced_updates!(node::Computed)
    input = node.parent
    input isa Input || error("Forced updates are only implemented for Inputs. Use ExplicitUpdate(data, :force) otherwise.")
    enable_forced_updates!(input)
    return
end
function enable_forced_updates!(input::Input)
    input.force_update = true
    return
end

function add_input!(attr::ComputeGraph, args...; force_update = false)
    add_input!(attr, Base.front(args), last(args))
    if force_update
        enable_forced_updates!(getindex(attr, Base.front(args)...).parent)
    end
    return attr
end

function add_input!(attr::ComputeGraphView, args...)
    combined = (attr.nested_trace.keys..., Base.front(args)...)
    return add_input!(attr.parent, combined, last(args))
end

function add_input!(attr::ComputeGraph, keys::Tuple, value)
    key = handle_nested_keys(attr, keys)
    return add_input!(attr, key, value)
end

add_input!(attr::ComputeGraph, key::Symbol, value) = _add_input!(identity, attr, key, value)

function add_input!(conversion_func, attr::ComputeGraph, args...; force_update = false)
    add_input!(conversion_func, attr, Base.front(args), last(args))
    if force_update
        enable_forced_updates!(getindex(attr, Base.front(args)...).parent)
    end
    return attr
end

function add_input!(conversion_func, attr::ComputeGraphView, args...)
    combined = (attr.nested_trace.keys..., Base.front(args)...)
    return add_input!(conversion_func, attr.parent, combined, last(args))
end

function add_input!(conversion_func, attr::ComputeGraph, keys::Tuple, value)
    key = handle_nested_keys(attr, keys)
    return add_input!(conversion_func, attr, key, value)
end

function add_input!(conversion_func, attr::ComputeGraph, key::Symbol, value)
    return _add_input!(conversion_func, attr, key, value)
end

function handle_nested_keys(attr::ComputeGraph, names::Tuple)
    if isempty(names)
        throw(
            ArgumentError(
                "`add_input!([callback], attr, names..., value)` requires at least one name and one value."
            )
        )
    end

    if !all(name -> name isa Symbol, names)
        first_bad = findfirst(name -> !isa(name, Symbol), names)
        throw(
            ArgumentError(
                "`add_input!([callback], attr, names..., value) requires all names to be Symbols, " *
                    "but name $(first_bad) is a $(typeof(names[first_bad]))."
            )
        )
    end

    if length(names) == 1
        return only(names)
    else
        add_key!(attr.nesting, names)
        return merged_key(names)
    end
end

function cleanup_nested_key!(attr::ComputeGraph, key::Symbol)
    names = Symbol.(split(string(key), '.'))
    delete_key!(attr.nesting, names)
    return
end

function _add_input!(func, attr::ComputeGraph, key::Symbol, value)
    @assert !(value isa Computed)
    if haskey(attr.inputs, key) || haskey(attr.outputs, key)
        # If this is a nested key we should not clean it up because it belongs
        # to something else
        error("Cannot attach input with name $key - already exists!")
    end

    output = Computed(key)
    input = Input(attr, key, value, func, output)
    output.parent = input
    output.parent_idx = 1
    # Needs to be Any, since input can change type
    attr.inputs[key] = input
    attr.outputs[key] = output
    return attr
end

function add_inputs!(conversion_func, attr::ComputeGraph; kw...)
    for (k, v) in pairs(kw)
        add_input!(conversion_func, attr, k, v)
    end
    return attr
end

compute_identity(inputs::NamedTuple, ::NamedTuple, @nospecialize(cached)) = values(inputs)
compute_identity(arg) = arg
compute_identity(args...) = args

function TypedEdge(edge::ComputeEdge, f::typeof(compute_identity), inputs)
    if length(inputs) != length(edge.outputs)
        error("A `compute_identity` callback requires the length of inputs and outputs to match.")
    end

    # use input refs as output refs so we don't even need to evaluate the callback
    for i in eachindex(values(inputs))
        edge.outputs[i].value = inputs[i]
        edge.outputs[i].dirty = true
    end

    return TypedEdge(f, inputs, edge.inputs_dirty, inputs, edge.outputs)
end

function locked_resolve!(edge::TypedEdge{IT, OT, typeof(compute_identity)}) where {IT, OT}
    # outputs are identical to inputs, so just copy the input state. To be safe
    # don't overwrite any `dirty = true` state with false (maybe a problem if
    # the input gets resolved?)
    for i in eachindex(edge.inputs_dirty)
        edge.output_nodes[i].dirty |= edge.inputs_dirty[i]
    end
    return
end

"""
    add_input!([callback], compute_graph, name::Symbol, node::Computed)

Connects an output `node` of another compute graph to the given `compute_graph`.

This does not create a settable input, meaning you cannot use
`update!(graph, name = new_value)` to update it. It is solely updated by the
connected node.
"""
function add_input!(attr::ComputeGraph, key::Symbol, value::Computed)
    if haskey(attr.outputs, key)
        error("Cannot attach throughput with name $key - already exists!")
    end
    register_computation!(compute_identity, attr, [value], [key])
    return attr
end

# for recipe -> primitive (mostly)
function add_input!(conversion_func, attr::ComputeGraph, key::Symbol, value::Computed)
    if haskey(attr.outputs, key)
        error("Cannot attach throughput with name $key - already exists!")
    end
    map!(conversion_func, attr, value, key)
    return attr
end

# Note: These don't work with add_input!(attr, key1, key2, ..., value)
function add_input!(attr::ComputeGraph, key::Symbol, value::ComputeGraphView)
    return add_input!(attr::ComputeGraph, (key,), value)
end
function add_input!(attr::ComputeGraph, nested_keys::Tuple{Vararg{Symbol}}, value::ComputeGraphView)
    for source_key in keys(value)
        add_input!(attr, (nested_keys..., source_key), getindex(value, source_key))
    end
    return attr
end
function add_input!(f, attr::ComputeGraph, key::Symbol, value::ComputeGraphView)
    return add_input!(f, attr::ComputeGraph, (key,), value)
end
function add_input!(f, attr::ComputeGraph, nested_keys::Tuple{Vararg{Symbol}}, value::ComputeGraphView)
    for source_key in keys(value)
        add_input!(f, attr, (nested_keys..., source_key), getindex(value, source_key))
    end
    return attr
end

"""
    add_input!([callback], compute_graph, name::Symbol, obs::Observable)

Connects an `Observable` as a input to the given `compute_graph`. The input will
be updated automatically whenever the observable updates. It can also be updated
through the usual `update!(graph, name = new_value)` call.

The Observable listener is set up with `priority = typemax(Int)-1` and
`Consume(false)`. This means it will take precedence over all but `typemax(Int)`
priority and not block later updates.
"""
function add_input!(attr::ComputeGraph, k::Symbol, obs::Observable)
    add_input!(attr, k, obs[])
    # typemax-1 so it doesn't get disturbed by other listeners but can still be
    # blocked by a typemax obs
    # Setting it to lower priority, axis and colorbar don't get the latest update
    # Still need to investigate why exactly
    of = on(obs; priority = typemax(Int) - 1) do new_val
        setproperty!(attr, k, new_val)
        return Consume(false)
    end
    push!(attr.observerfunctions, of)
    return attr
end

function add_input!(f, attr::ComputeGraph, k::Symbol, obs::Observable)
    add_input!(f, attr, k, obs[])
    of = on(obs, priority = typemax(Int) - 1) do new_val
        setproperty!(attr, k, new_val)
        return Consume(false)
    end
    push!(attr.observerfunctions, of)
    return attr
end

"""
    add_constant!(graph, name::Symbol, value)
    add_constant!(graph, nested_names::Symbol..., value)

Adds a constant to the Graph. A constant is not connected to an `Input` and thus
can't change through compute graph resolution.
"""
function add_constant!(attr::ComputeGraph, k::Symbol, value)
    haskey(attr, k) && return
    map!(() -> value, attr, Symbol[], k)
    return attr
end

function add_constant!(attr::ComputeGraph, keys::Tuple, value)
    combined = handle_nested_keys(attr, keys)
    return add_constant!(attr, combined, value)
end

function add_constant!(attr::ComputeGraph, args...)
    return add_constant!(attr, Base.front(args), last(args))
end

function add_constant!(attr::ComputeGraphView, args...)
    combined = (attr.nested_trace.keys..., Base.front(args)...)
    return add_constant!(attr.parent, combined, last(args))
end

function add_constants!(attr::ComputeGraph; kw...)
    for (k, v) in pairs(kw)
        add_constant!(attr, k, v)
    end
    return attr
end

get_callback(computed::Computed) = hasparent(computed) ? computed.parent.callback : nothing

"""
    register_computation!(callback, compute_graph, input_names, output_names)

Registers a new computation which transforms the given inputs to a new set of
outputs. Both the inputs and outputs are referred to by name. The inputs must
exist when the function is called. The outputs should usually created by this
function.

The callback function must accept 3 arguments:
- `inputs::NamedTuple` which contains the `input_names` and input values in the order given to `register_computation`
- `changed::NamedTuple` which a `Bool` per input name signifying whether the input has been updated since the last execution of `callback`
- `cached::Tuple` which contain the last outputs returned by function. If no previous outputs exist `cached = nothing`.

Note that `inputs` and `cached` always wrap input and outputs values in `Ref`,
so you need to always dereference them.

## Example:

```julia
graph = ComputeGraph()
add_input!(graph, :input1, 1)
add_input!(graph, :input2, 1)

register_computation!(graph, [:input1, :input2], [:output1, :output2]) do inputs, changed, cached
    input1, input2 = inputs
    has_input1_changed, has_input2_changed2 = changed
    cached_output1, cached_output2 = cached

    # compute new outputs

    return (new_output1, new_output2)
end
```

See also: [`add_input!`](@ref), [`map!`](@ref)
"""
function register_computation!(f, attr::ComputeGraph, inputs::Vector{Symbol}, outputs::Vector{Symbol})
    if !all(k -> haskey(attr.outputs, k), inputs)
        missing_keys = filter(k -> !haskey(attr.outputs, k), inputs)
        error("Could not register computation: Inputs $missing_keys not found.")
    end
    _inputs = Computed[attr.outputs[k] for k in inputs]
    register_computation!(f, attr, _inputs, outputs)
    return
end

get_node(attr::ComputeGraph, name::Symbol) = attr.outputs[name]
get_node(attr::ComputeGraph, keys::Tuple) = attr.outputs[merged_key(keys)]
get_node(::AbstractComputeGraph, node::Computed) = node

get_node(attr::ComputeGraph, path::Symbol, name::Symbol) = get_node(attr, merged_key(path, name))
get_node(attr::ComputeGraph, path::Symbol, keys::Tuple) = get_node(attr, path, merged_key(keys))
get_node(attr::ComputeGraph, path::Symbol, node::Computed) = node

function get_node(view::ComputeGraphView, name::Symbol)
    return get_node(view.parent, merged_key(view.nested_trace), name)
end
function get_node(view::ComputeGraphView, keys::Tuple)
    return get_node(view.parent, merged_key(view.nested_trace), keys)
end

convert_to_nodes(attr::ComputeGraph, inputs) = get_node.(Ref(attr), inputs)
convert_to_nodes(attr::ComputeGraph, path, inputs) = get_node.(Ref(attr), Ref(path), inputs)
function convert_to_nodes(view::ComputeGraphView, inputs)
    return convert_to_nodes(view.parent, merged_key(view.nested_trace), inputs)
end

# [computed, symbol] is an Any Vector so no eltype here
function register_computation!(f, attr::ComputeGraph, inputs::Vector, outputs::Vector{Symbol})
    _inputs = convert_to_nodes(attr, inputs)
    register_computation!(f, attr, _inputs, outputs)
    return
end

to_nested_trace(s::Symbol) = (s,)
to_nested_trace(t::Tuple) = t
to_nested_trace(v::Vector{Symbol}) = tuple(v...)
to_nested_trace(view::ComputeGraphView) = to_nested_trace(view.nested_trace.keys)
to_nested_trace(a, b) = tuple(to_nested_trace(a)..., to_nested_trace(b)...)

function handle_nested_outputs(view::ComputeGraphView, outputs::Vector, path::Symbol = merged_key(view.nested_trace))
    attr = view.parent

    # combine Symbol or Tuple references with view and lower them to Symbols in
    # the parent graph. If a nested node is used, register it
    added_nesting = Symbol[]
    _outputs = Vector{Symbol}(undef, length(outputs))
    for (i, namelike) in enumerate(outputs)
        combined_name = merged_key(path, namelike)
        if !haskey(view, namelike)
            add_key!(attr.nesting, to_nested_trace(view, namelike))
            push!(added_nesting, combined_name)
        end
        _outputs[i] = combined_name
    end

    return added_nesting, _outputs
end

function handle_nested_outputs(attr::ComputeGraph, outputs::Vector)
    # Register nesting for Tuple inputs and lower them to Symbols
    added_nesting = Symbol[]
    _outputs = Vector{Symbol}(undef, length(outputs))
    for (i, namelike) in enumerate(outputs)
        if namelike isa Symbol
            _outputs[i] = namelike
        elseif namelike isa Tuple
            combined_name = merged_key(namelike)
            if !haskey(attr.nesting, namelike...)
                add_key!(attr.nesting, namelike)
                push!(added_nesting, combined_name)
            end
            _outputs[i] = combined_name
        else
            error("Could not process output $namelike - must be a Symbol or Tuple.")
        end
    end

    return added_nesting, _outputs
end

function register_computation!(f, attr::AbstractComputeGraph, inputs::Vector, outputs::Vector)
    _inputs = convert_to_nodes(attr, inputs)
    added_nesting, _outputs = handle_nested_outputs(attr, outputs)

    try
        register_computation!(f, root(attr), _inputs, _outputs)
    catch e
        # If we fail to create the computation we remove the nesting information
        # we added
        for name in added_nesting
            cleanup_nested_key!(root(attr), name)
        end
        rethrow(e)
    end
    return
end

function check_boxed_values(f)
    names = propertynames(f)
    name_values = map(x -> x => getfield(f, x), names)
    boxed = filter(p -> p[2] isa Core.Box, name_values)
    return if !isempty(boxed)
        boxed_str = map(boxed) do (k, v)
            box = isdefined(v, :contents) ? typeof(v.contents) : "#undef"
            return "$(k)::Core.Box($(box))"
        end
        error("Cannot register computation: Callback function cannot use boxed values: $(first(methods(f))), $(join(boxed_str, ",")). This might be caused by a variable of the same name existing inside and outside a `do ... end` block.")
    end
end

macro ifelse_enabled(enabled_expr, disabled_expr = :())
    if ENABLE_COMPUTE_CHECKS
        return esc(enabled_expr)
    else
        return esc(disabled_expr)
    end
end

function assert_same_computation(@nospecialize(f), attr::ComputeGraph, inputs, outputs)
    # Check this so we can type assert later
    if any(k -> haskey(attr.inputs, k), outputs)
        input_nodes = [k for k in outputs if haskey(attr.inputs, k)]
        error("One or multiple edge outputs already exist as graph inputs: $input_nodes")
    end

    e = attr.outputs[outputs[1]].parent::ComputeEdge

    # Check that the edge is shared
    if any(k -> attr.outputs[k].parent::ComputeEdge !== e, outputs)
        # bad_keys = join([k for k in outputs if attr.outputs[k].parent != e], ", ")
        error("Cannot register computation: $outputs already have multiple different parent compute edges.")
    end

    # Check that the requested inputs are the inputs of the new edge
    if length(e.inputs) != length(inputs) || e.inputs != inputs
        error(
            "Cannot register computation: Outputs already have a parent compute edge with different inputs.\n" *
                "   New: (" * join([n.name for n in inputs], ", ") * ") -> (" * join(outputs, ", ") * ")\n" *
                "   Old: (" * join([n.name for n in e.inputs], ", ") * ") -> (" * join([n.name for n in e.outputs], ", ") * ")"
        )
    end

    # Check that the same callback is used
    # TODO: === is much faster, but why?
    if @ifelse_enabled(e.callback != f, e.callback !== f)
        # We should only care about input arg types...
        func1, loc1 = edge_callback_to_string(f, (NamedTuple, NamedTuple, Nothing))
        func2, loc2 = edge_callback_to_string(e)
        error(
            "Cannot register computation: The outputs already have a parent compute edge using " *
                "a different callback function.\n  Given: $func1 $loc1\n  Found: $func2 $loc2\n  $(methods(f))"
        )
    end

    # edge already exists so we can
    return
end

function register_computation!(f, attr::ComputeGraph, inputs::Vector{Computed}, outputs::Vector{Symbol})
    @ifelse_enabled(check_boxed_values(f))

    if any(k -> haskey(attr.outputs, k), outputs)
        N_existing = count(k -> haskey(attr.outputs, k) && hasparent(attr.outputs[k]), outputs)
        if N_existing == 0
            # fine, we won't be overwriting an edge
        elseif N_existing != length(outputs)
            existing = [k for k in outputs if haskey(attr.outputs, k) && hasparent(attr.outputs[k])]
            combined = join(existing, ", ")
            error("Cannot register computation: Some outputs already have parent compute edges: $combined")
        else

            assert_same_computation(f, attr, inputs, outputs)

            # edge already exists so we can return
            return
        end
    end

    new_edge = ComputeEdge(f, attr, inputs)

    for input in inputs
        @assert hasparent(input) "Computed should be guaranteed to have a parent edge, but does not"
        # Edges can have multiple outputs so multiple inputs of this edge could
        # come from the same edge
        any(x -> x === new_edge, input.parent.dependents) && continue
        push!(input.parent.dependents, new_edge)
    end

    # use order of namedtuple, which should not change!
    for (i, symbol) in enumerate(outputs)
        # create an uninitialized Ref, which gets replaced by the correctly strictly typed Ref on first resolve
        value = get!(attr.outputs, symbol, Computed(symbol))
        value.parent = new_edge
        value.parent_idx = i
        value.dirty = true
        push!(new_edge.outputs, value)
    end

    return
end

struct MapFunctionWrapper{pack, FT} <: Function
    user_func::FT
    MapFunctionWrapper(f::FT, pack = true) where {FT} = new{pack, FT}(f)
end

function (x::MapFunctionWrapper{true})(inputs, @nospecialize(changed), @nospecialize(cached))
    result = x.user_func(values(inputs)...)
    return (result,)
end
function (x::MapFunctionWrapper{false})(inputs, @nospecialize(changed), @nospecialize(cached))
    result = x.user_func(values(inputs)...)
    return result
end

const InputNodeTypes = Union{Computed, Symbol, Tuple{Vararg{Symbol}}}
const OutputNodeTypes = Union{Symbol, Tuple{Vararg{Symbol}}}

"""
    map!(f, compute_graph, inputs, outputs; init=nothing)

Registers a new ComputeEdge in the `compute_graph` which connects one or multiple
`inputs` to one or multiple `outputs`.

Inputs can be:
- a `Symbol` referring to a node in the `compute_graph`
- a `Tuple{Vararg{Symbol}}` referring to a nested node in the `compute_graph`
- a `Computed`, i.e. a node of any compute graph
- a `Vector` containing any of the above

Outputs can be a `Symbol`, `Tuple{Vararg{Symbol}}` or `Vector` of the former.
They can not be compute nodes.

If a `ComputeGraphView` is passed as the `compute_graph` any `Symbol` and `Tuple`
input and output will be relative to the view. For example, input `:b` will be
interpreted as `graph.a.b` if `graph.a` is passed as the `compute_graph`.

The callback function `f` will be called with the values of the inputs as arguments.
If `outputs` is a single `Symbol` or `Tuple`, the function is expected to return
one output. Otherwise it is expected to return a tuple of outputs, one for each
target specified in `outputs`.

Optionally `init` can be specified to immediately initialize the outputs without
calling `f`. For a single output the value can be provided directly. For multiple
outputs a tuple with matching size is needed, like with `f`.

```julia
graph = ComputeGraph()
add_input!(graph, :input1, 2)
add_input!(graph, :input2, 1)

other_graph = ComputeGraph()
add_input!(other_graph, :input, 3)

map!(x -> 2x, graph, :input1, :output1)
map!((x, y) -> x+y, graph, [:input1, other_graph.input], :output2)
map!((x, y) -> (x+y, x-y), graph, [:input1, :input2], [:output3, :output4])

# With initial values
map!(x -> 2x, graph, :input1, :output5; init=0)
map!((x, y) -> (x+y, x-y), graph, [:input1, :input2], [:output6, :output7]; init=(0, 0))

# Nesting
add_input!(graph, :nested, :input1, -1)
add_input!(graph, :nested, :input2, -2)
map!(+, graph, [(:nested, :input1), :input1], (:nested, :output1))
map!(+, graph.nested, [:input2, graph.input2], :output2)
```

See also: [`add_input!`](@ref), [`register_computation!`](@ref)
"""
function Base.map!(f, attr::AbstractComputeGraph, input::InputNodeTypes, output::OutputNodeTypes; init = nothing)
    register_computation!(MapFunctionWrapper(f), attr, [input], [output])
    isnothing(init) || unsafe_init!(attr, output, init)
    return attr
end

function Base.map!(f, attr::AbstractComputeGraph, inputs::Vector, output::OutputNodeTypes; init = nothing)
    register_computation!(MapFunctionWrapper(f), attr, inputs, [output])
    isnothing(init) || unsafe_init!(attr, output, init)
    return attr
end

function Base.map!(f, attr::AbstractComputeGraph, inputs::Vector, outputs::Vector; init = nothing)
    register_computation!(MapFunctionWrapper(f, false), attr, inputs, outputs)
    isnothing(init) || unsafe_init!(attr, outputs, init)
    return attr
end

function Base.map!(f, attr::AbstractComputeGraph, inputs::InputNodeTypes, outputs::Vector; init = nothing)
    register_computation!(MapFunctionWrapper(f, false), attr, [inputs], outputs)
    isnothing(init) || unsafe_init!(attr, outputs, init)
    return attr
end

function unsafe_init!(graph::AbstractComputeGraph, name_or_node, val)
    return unsafe_init!(get_node(graph, name_or_node), val)
end

function unsafe_init!(graph::AbstractComputeGraph, name_or_nodes::Vector, values)
    if !(values isa Tuple && length(values) == length(name_or_nodes))
        error("Initial values for map! must be given as a Tuple matching the number of outputs")
    end

    for (name_or_node, val) in zip(name_or_nodes, values)
        unsafe_init!(get_node(graph, name_or_node), val)
    end
    return
end

function take_last!(channel::Channel; wait = false)
    return lock(channel) do
        result = wait ? take!(channel) : nothing
        while isready(channel)
            result = take!(channel)
        end
        return result
    end
end

"""
    map_latest!(f, compute_graph::ComputeGraph, inputs::Vector{Symbol}, outputs::Vector{Symbol}; spawn=false, init=nothing)

Registers an asynchronous computation in the `compute_graph` that processes only the
most recent input changes, skipping intermediate updates if the computation is still running.

This is useful for expensive computations where intermediate results are not needed, such as:
- Heavy image processing or rendering operations
- Slow network requests
- Complex data analysis or simulations

## Behavior

When inputs change:
- any new value is put in a queue to be computed
- If multiple updates occur while computing, only the **most recent** input values are
  kept; intermediate values are discarded
- The outputs return cached values while the computation is in progress
- finishing a computation invalidates the graph, so on the next poll the latest result is returned

The first call to retrieve outputs will block until the initial computation completes,
unless `init` is provided.

## Arguments
- `f`: Callback function that receives input values as individual arguments and returns
  a tuple of output values
- `compute_graph`: The compute graph to register the computation in
- `inputs`: Vector of Symbol names referring to input nodes in the graph
- `outputs`: Vector of Symbol names for the output nodes to be created
- `spawn=false`: If `true`, runs the background worker on a separate thread. If `false`,
  runs an async task.
- `init=nothing`: Optional tuple of initial values for the output nodes. Must match the
  number of outputs. This allows the outputs to have a value before the first computation
  completes.

## Example

```julia
graph = ComputeGraph()
add_input!(graph, :image_data, initial_image)
add_input!(graph, :filter_strength, 1.0)

# Register expensive async computation that skips intermediate updates
map_latest!(graph, [:image_data, :filter_strength], [:filtered_image]) do img, strength
    # This expensive operation only runs on the latest inputs
    result = expensive_filter(img, strength)
    return (result,)
end

# Rapidly update inputs - only the final values will be processed
for i in 1:100
    update!(graph, filter_strength = i / 10.0)
end
graph[:filtered_image][] # poll to trigger computation queue
sleep(0.1) # wait for a computation to finish to not get old result
result = graph[:filtered_image][]
```
"""
function map_latest!(f, attr::ComputeGraph, inputs::Vector{Computed}, outputs::Vector{Symbol}; spawn = false, init = nothing)
    update_key = Symbol(:_update_trigger_, string(hash((inputs, outputs))))
    add_input!(attr, update_key, time())
    # TODO, should both channels be size 1?
    # Channel for input requests
    input_channel = Channel{Any}(2)
    # Background worker task that processes computation requests
    result_channel = Channel(2; spawn = spawn) do result_channel
        while isopen(input_channel)
            try
                # Take the first item (blocking if empty)
                fetched_inputs = take_last!(input_channel; wait = true)
                # Process the most recent inputs
                result = f(fetched_inputs...)
                # Put result in the result channel
                put!(result_channel, result)
                # Notify that we got a new value, for the below computation to run
                update!(attr, update_key => time())
            catch e
                @error "Error in background computation task" exception = (e, catch_backtrace())
            end
        end
    end

    register_computation!(attr, [update_key, inputs...], outputs) do inputs, changed, last
        user_inputs = tail(values(inputs))
        # Blocking wait for first result, this can't be avoided, since the node needs to be initialized
        isnothing(last) && return f(user_inputs...)
        # Always queue new computation unless no user inputs changed
        if any(tail(values(changed)))
            take_last!(input_channel) # discard old inputs
            put!(input_channel, user_inputs)
        end
        # Always return the last result
        # if there is non, this returns nothing, which signals no update
        return take_last!(result_channel)
    end

    if !isnothing(init)
        @assert init isa Tuple && length(init) == length(outputs) "Initial values for map_latest! must be given as a Tuple matching the number of outputs"
        for (i, val) in enumerate(init)
            unsafe_init!(attr.outputs[outputs[i]], val)
        end
    end

    return
end

function map_latest!(f, attr::AbstractComputeGraph, inputs::Vector, outputs::Vector; kwargs...)
    _inputs = convert_to_nodes(attr, inputs)
    added_nesting, _outputs = handle_nested_outputs(attr, outputs)

    try
        map_latest!(f, root(attr), _inputs, _outputs; kwargs...)
    catch e
        # If we fail to create the computation we remove the nesting information
        # we added
        for name in added_nesting
            cleanup_nested_key!(root(attr), name)
        end
        rethrow(e)
    end
    return
end


function Base.empty!(attr::ComputeGraph)
    # empty!(attr.inputs)
    # empty!(attr.outputs)
    for (name, obs) in attr.observables
        Observables.clear(obs)
    end
    empty!(attr.observables)
    for of in attr.observerfunctions
        Observables.off(of)
    end
    return empty!(attr.observerfunctions)
end

"""
    delete!(graph::ComputeGraph, key::Symbol[; force = false, recursive = false])

Deletes a node from the given graph based on its name.

If `recursive = true` all child nodes of the selected node are deleted. If
`force = true` all siblings (outputs from the same parent edge) are deleted.
If either exists without the respective option being true an error will be thrown.
"""
function Base.delete!(attr::ComputeGraph, key::Symbol; force::Bool = false, recursive::Bool = false)
    haskey(attr.outputs, key) || throw(KeyError(key))
    @lock GLOBAL_LOCK begin
        _delete!(attr, attr.outputs[key], force, recursive)
    end
    return attr
end

function _delete!(attr::ComputeGraph, node::Computed, force::Bool, recursive::Bool)
    @assert hasparent(node)
    _delete!(attr, node.parent, force, recursive)
    return attr
end

function validate_deletion(edge::ComputeEdge, force::Bool, recursive::Bool)
    force && recursive && return
    if !(length(edge.outputs) == 1 || force)
        error("Cannot delete node because it or one of its dependents has siblings. Set `force = true` to also delete siblings.")
    end
    if !(recursive || isempty(edge.dependents))
        error("Cannot delete node because it has children. Set `recursive = true` to also delete its children.")
    end
    return foreach(e -> validate_deletion(e, force, recursive), edge.dependents)
end

function validate_deletion(edge::Input, force::Bool, recursive::Bool)
    force && recursive && return
    if !(recursive || isempty(edge.dependents))
        error("Cannot delete node because it has children. Set `recursive = true` to also delete its children.")
    end
    return foreach(e -> validate_deletion(e, force, recursive), edge.dependents)
end

function _delete!(attr::ComputeGraph, edge::AbstractEdge, force::Bool, recursive::Bool)
    validate_deletion(edge, force, recursive)
    return unsafe_delete!(attr, edge)
end

function unsafe_delete!(attr::ComputeGraph, edge::ComputeEdge)
    @lock edge.lock begin
        # all dependents become invalid as their parent computation no longer runs
        for dependent in edge.dependents
            unsafe_delete!(attr, dependent)
        end

        # deregister this edge as a dependency of its parents
        for computed in edge.inputs
            @assert hasparent(computed)
            parent_edge = computed.parent
            filter!(e -> e !== edge, parent_edge.dependents)
        end

        # Delete output nodes of this edge
        for computed in edge.outputs
            k = computed.name
            @assert haskey(attr.outputs, k) && attr.outputs[k] === computed
            delete!(attr.outputs, k)
        end
    end

    return attr
end

function unsafe_delete!(attr::ComputeGraph, edge::Input)
    @lock edge.lock begin
        # all dependents become invalid as their parent computation no longer runs
        for dependent in edge.dependents
            unsafe_delete!(attr, dependent)
        end

        # Delete output node of this edge
        k = edge.name
        @assert haskey(attr.outputs, k) && attr.outputs[k] === edge.output
        delete!(attr.outputs, k)

        # Delete Input
        @assert haskey(attr.inputs, k) && attr.inputs[k] === edge
        delete!(attr.inputs, k)
    end

    return attr
end

"""
    unsafe_disconnect_parents!(graph)

Removes every reference to this graph from every connected parent graph. This is
meant to prepare the given graph for garbage collection.

After calling this function, the graph will be in a broken state. Edges
connecting this graph to parent graphs still exist with references to parent
graphs, but they can no longer be triggered.
"""
function unsafe_disconnect_from_parents!(attr::ComputeGraph)
    for comp in values(attr.outputs)
        if hasparent(comp)
            unsafe_disconnect_parent_graph_nodes!(attr, comp.parent)
        end
    end
    return
end

unsafe_disconnect_parent_graph_nodes!(attr::ComputeGraph, edge::Input) = nothing
function unsafe_disconnect_parent_graph_nodes!(attr::ComputeGraph, edge::ComputeEdge)
    for input in edge.inputs
        if !haskey(attr.outputs, input.name) || !(input in values(attr.outputs))
            unsafe_atomic_delete!(edge)
        end
    end
    return
end

function unsafe_atomic_delete!(edge::ComputeEdge)
    # deregister this edge as a dependency of its parents
    for computed in edge.inputs
        if hasparent(computed)
            parent_edge = computed.parent
            filter!(e -> e !== edge, parent_edge.dependents)
        end
    end

    return
end


is_initialized(node::Computed) = isdefined(node, :value) && isassigned(node.value)

"""
    unsafe_init!(node::Computed, value)

Initializes a node to the given value. If this causes all outputs of the parent
compute edge to be initialized, the edge will be initialized without calling its
callback.

This function makes no checks to confirm that the given value matches the type
returned by the parent edge callback.
"""
function unsafe_init!(node::Computed, value)
    if isdefined(node, :value)
        error("Node already initialized.")
    else
        node.value = value isa RefValue ? value : RefValue(value)
    end

    return unsafe_init!(node.parent)
end

function unsafe_init!(edge::ComputeEdge)
    # We can only mark the edge as initialized if all the outputs have been
    # initialized
    if !all(is_initialized, edge.outputs)
        return false
    end

    lock_key = lock_before_resolve!(edge)
    try
        try_resolve_parents(edge, lock_key)
        try
            edge.typed_edge[] = TypedEdge_no_call(edge)
        catch e
            edge.dirty[] = true
            rethrow(e)
        finally
            foreach(e -> unlock_input!(e, lock_key), edge.inputs)
            edge.should_resolve_now[] = false
            fill!(edge.inputs_dirty, false)
            for dep in edge.dependents
                mark_input_dirty!(edge, dep)
            end
            foreach(comp -> comp.dirty = false, edge.outputs)
        end
    finally
        unlock(edge.lock, lock_key)
    end
    return true
end

function unsafe_init!(input::Input)
    input.dirty = false
    input.output.dirty = true
    for edge in input.dependents
        mark_input_dirty!(input, edge)
    end
    input.output.dirty = false
    return true
end

function TypedEdge_no_call(edge::ComputeEdge)
    inputs = let
        N = length(edge.inputs)
        names = ntuple(i -> edge.inputs[i].name, N)
        values = ntuple(i -> edge.inputs[i].value, N)
        NamedTuple{names}(values)
    end

    outputs = let
        N = length(edge.outputs)
        names = ntuple(i -> edge.outputs[i].name, N)
        values = ntuple(i -> edge.outputs[i].value, N)
        NamedTuple{names}(values)
    end

    return TypedEdge(edge.callback, inputs, edge.inputs_dirty, outputs, edge.outputs)
end

"""
    set_type!(node::Computed, type)

Initialize a compute graph `node` to the given `type`.

```
map!(x -> rand([1, 1.0, "1"]), graph, :input, :output)
set_type!(graph.output, Union{Int, Float64, String})
```
"""
function set_type!(node::Computed, T::Type)
    if isdefined(node, :value)
        error("Node already initialized.")
    else
        node.value = Ref{T}()
    end
    return
end

include("io.jl")
include("observables_compat.jl")
include("utils.jl")

export Computed, ComputeEdge
export ComputeGraph
export register_computation!, map_latest!
export add_input!, add_inputs!, add_constant!, add_constants!
export update!

end
