################################################################################
### DocumentedAttributes definition & generation
################################################################################

"""
    Inherit([callback = identity], keys, [fallback = NoFallback()])

Marks an attribute definition as inheriting from a parent theme. Objects of this
type are generated by `@inherit [callback] keys [fallback]` within `@recipe`,
`@Block` and `@DocumentedAttributes`.

Arguments:
- `callback` is an optional callback that applies to the inherited value before
    it is used as an attribute
- `keys` is a tuple of keys referring to a potentially nested attribute in the
    `theme(scene)` or the global `theme(nothing)`
- `fallback` is an optional value used if the value can't be inherited. If it is
    not provided it defaults to `NoFallback()` which requires the value to be
    inherited. `fallback` can also be another `Inherit`.
"""
struct Inherit{N}
    callback::Any
    keys::NTuple{N, Symbol}
    fallback::Any
end
struct NoFallback end

Inherit(keys::Tuple{Vararg{Symbol}}) = Inherit(identity, keys, NoFallback())
Inherit(keys::Tuple{Vararg{Symbol}}, fallback) = Inherit(identity, keys, fallback)
Inherit(f, keys::Tuple{Vararg{Symbol}}) = Inherit(f, keys, NoFallback())

# For replacing `@inherit x` with `@inherit :x`
default_key_expr(x::Symbol) = :(($(QuoteNode(x)),))
default_key_expr(x::QuoteNode) = :(($x,))
function default_key_expr(expr::Expr)
    if !(expr.head == :tuple && all(x -> x isa QuoteNode, expr.args))
        error("$expr is not a valid inheritance key")
    end
    for i in eachindex(expr.args)
        expr.args[i] = ifelse(expr.args[i] isa Symbol, QuoteNode(expr.args[i]), expr.args[i])
    end
    return expr
end

# parse `name = <this part>`
# which may be `@attributes begin ... end`
# or some form of `@inherit ...`
function get_default_expr(default, attribute_path)
    if MacroTools.@capture(default, @attributes attrblock_)
        return build_documented_attributes(attrblock, attribute_path)
    else
        return get_default_expr_no_nesting(default, attribute_path, default)
    end
end

# Parses specifically `@inherit ...`  and its compat forms
function get_default_expr_no_nesting(expr, attribute_path, full_expr)
    # This is split off to allow Inherit(key, Inherit(...)) in some capacity
    if MacroTools.@capture(expr, inherit(scene_, key_, fallback_))
        # This was only supported with fallback by Blocks
        fb = get_default_expr_no_nesting(fallback, attribute_path, full_expr)
        return :(Makie.Inherit($(default_key_expr(key)), $fb))
    elseif MacroTools.@capture(expr, map(f_, inherit(scene_, key_, fallback_)))
        # This was only supported with fallback by Blocks
        fb = get_default_expr_no_nesting(fallback, attribute_path, full_expr)
        return :(Makie.Inherit($f, $(default_key_expr(key)), $fb))
    elseif MacroTools.@capture(expr, @inherit(key_, fallback_))
        # This was only supported with fallback by Blocks (?)
        fb = get_default_expr_no_nesting(fallback, attribute_path, full_expr)
        return :(Makie.Inherit($(default_key_expr(key)), $fb))
    elseif MacroTools.@capture(expr, theme(scene_, key_))
        return :(Makie.Inherit($(default_key_expr(key))))

    elseif MacroTools.@capture(expr, @inherit callback_ key_ fallback_)
        fb = get_default_expr_no_nesting(fallback, attribute_path, full_expr)
        return :(Makie.Inherit($callback, $(default_key_expr(key)), $fb))
    elseif MacroTools.@capture(expr, @inherit key_ fallback_)
        # TODO: How do we figure out if this is @inherit callback key instead?
        fb = get_default_expr_no_nesting(fallback, attribute_path, full_expr)
        return :(Makie.Inherit($(default_key_expr(key)), $fb))
    elseif MacroTools.@capture(expr, @inherit key_)
        return :(Makie.Inherit($(default_key_expr(key))))

    elseif MacroTools.@capture(expr, @attributes attrblock_)
        path = join(attribute_path, " -> ")
        error("`@attributes` cannot be used with an @inherit (or similar) block. Used in $path = $full_expr.")
    elseif MacroTools.@capture(expr, Makie.defaultfont())
        path = join(attribute_path, " -> ")
        @warn """
            Using `Makie.defaultfont()` as an attribute default in `@recipe` or `@Block` causes segfaults due to invalid font pointers from caching.
            Replacing it with `\"default\"` in `$path = $full_expr`"
            """
        return :("default")
    else
        return esc(expr)
    end
end

"""
    AttributeMetadata(docstring, default_value, default_expr, type)

Encapsulates information given for attributes in `@DocumentedAttributes`,
`@recipe` or `@Block`.

Arguments:
- `docstring` docstring defined for an attribute within the parent macro call.
    Defaults to `nothing` if no docstring is defined.
- `default_value` is the value given to the attribute in the parent macro. Can
    be `DocumentedAttributes` for nested attributes, a literal or a `Inherit`
    for values inherited from a theme.
- `default_expr` is a String of the expression used to generate the default value.
    For `DocumentedAttributes` this is shortened to `Attributes(...)`
- `type` is a type annotation optionally given to an attribute. Defaults to `Any`.
"""
Base.@kwdef struct AttributeMetadata
    docstring::Union{Nothing, String}
    default_value::Any
    default_expr::String # stringified expression, just needed for docs purposes
    type::Type
end

update_metadata(am1::AttributeMetadata, am2::AttributeMetadata) = AttributeMetadata(
    am2.docstring === nothing ? am1.docstring : am2.docstring,
    am2.default_value,
    am2.default_expr, # TODO: should it be possible to overwrite only a docstring by not giving a default expr?
    am2.type
)
function set_metadata!(d, key, am)
    d[key] = haskey(d, key) ? update_metadata(d[key], am) : am
    return
end

function default_expr_string(default)
    is_macrocall = default isa Expr && default.head === :macrocall
    if is_macrocall && default.args[1] === Symbol("@attributes")
        # for normal recipes
        return "Attributes(...)"
    elseif MacroTools.@capture(default, Attributes(args__))
        # for old recipes
        return "Attributes(...)"
    elseif MacroTools.@capture(default, Makie.DocumentedAttributes(args__))
        # for old recipes, maybe also better to have in general?
        return "Attributes(...)"
    else
        return string(MacroTools.prewalk(MacroTools.rmlines, default))
    end
end

default_expr_string(x::String) = repr(x)

"""
    DocumentedAttributes(dict)

Encapsulates attributes with metadata generated by `@DocumentedAttributes`,
`@recipe`, `@Block` macros or by the `@attributes` identifier within the former.

See `?@DocumentedAttributes`
"""
struct DocumentedAttributes
    d::Dict{Symbol, AttributeMetadata}
end

DocumentedAttributes() = DocumentedAttributes(Dict{Symbol, AttributeMetadata}())
function DocumentedAttributes(args::Pair{Symbol, AttributeMetadata}...)
    return DocumentedAttributes(Dict{Symbol, AttributeMetadata}(args...))
end

"""
    @DocumentedAttributes begin ... end

Generates `DocumentedAttributes` which encapsulate default attributes for a
plot or block.

## Macro Syntax

Attributes are given line by line, with each line defining at least the name
and default value of the attribute with `name = default_value`. Optionally, the
attribute may define a docstring in the preceding line:

    "Documentation for color"
    color = :red

The default value can be inherited from the parent theme of the plot or block
with the `@inherit [callback] key [fallback]` identifier. The `key` is a Symbol
or tuple of Symbols referring to the inherited value from the theme. `fallback`
is an optional default value if key cannot be found. It can also be another
`@inherit`. `callback` is an optional transformation that applies to the
inherited value.

    colormap = @inherit :colormap
    colormap = @inherit :colormap :viridis
    rticklabelsize = @inherit((:Axis, :xticklabelsize), @inherit :fontsize 16)
    titlesize = @inherit(x -> 1.2x, :fontsize, 16)

The default value can nest using `@attributes`:

    outer = @attributes begin
        inner = 1
    end

This will generate `outer.inner` as an attribute in the plot or block that uses
the attributes generated here. Both `outer` and `inner` may be documented.

`DocumentedAttributes` from an outside source can be included as attributes
using splatting (`...`). This is typically done with "mixin" functions,
`Makie.filtered_attributes` or `Makie.documented_attribute`:

    Makie.mixin_colormap_attributes()...
    Makie.filtered_attributes(Scatter, exclude = (:colormap, :colorscale, :colorrange, :lowclip, :highclip, :nan_color, :alpah))...

Note that these expressions will error if they include attributes that are already
defined. This is meant to prevent accidental overwrites from mixins. Inversely, if
an attribute added by a mixin is later also added explicitly, the later addition
will overwrite the earlier entry. If the later addition does not include a
docstring, the docstring from the ealier mixin will be preserved.

Attributes can be marked with a type by annotating their name. This is controls
the conversions in **Blocks** but is irrelevant to plots.

    color::RGBAf = :red

## Macro Examples

The macro itself is typically only used in "mixin" functions:

    function mixin_my_attributes()
        @DocumentedAttributes begin
            "my color"
            my_color = :red
            "my colormap"
            colormap = @inherit :colormap :viridis
        end
    end

In `@recipe` the `begin ... end` block is processed in the same way as
`@DocumentedAttributes`. All the rules above thus apply to it:

    @recipe MyPlot (position,) begin
        Makie.documented_attributes(Scatter)...
        "my plot attribute"
        attr = 1
    end

In `@Block` the outer most `@attributes begin ... end` block is treated as an
`@DocumentedAttributes begin ... end` block:

    @Block MyAxis begin
        @attributes begin
            "sets the title of MyAxis"
            title = ""
            x = @attributes begin
                axis = @attributes begin
                    "Sets the label of the x axis"
                    label = "X"
                    "Sets the fontsize of the x axis label"
                    fontsize = 16
                end
            end
        end
    end

## Theming

When documented are used in a plot or block, they are merged with various themes
as well as values given by the user through keyword arguments. From highest to
lowest priority the following sources are merged:

1. User passed values, e.g. `myplot(..., attribute = 1)`
2. Attributes defined in `theme(scene)[:MyPlot]` (if it exists)
3. Attributes defined in the global `theme(nothing)[:MyPlot]` (if it exists)
4. The default values defined with `@DocumentedAttributes/@recipe/@Block`
5. If an attribute inherits, the default set in `theme(scene)`
6. If an attribute inherits, the default set in the global `theme(nothing)`
7. The `fallback` of an inherited attribute

Note that for 5 and 6, the names looked up in the respective themes are not the
name of the attribute but the name set in `@inherit name`.

Note that `@inherit` can be nested, so the fallback may loop through steps 5-7
again with different names to look up.
"""
macro DocumentedAttributes(expr::Expr)
    return build_documented_attributes(expr)
end

function build_documented_attributes(expr::Expr, attribute_path = tuple())
    if !(expr isa Expr && expr.head === :block)
        throw(ArgumentError("Argument is not a begin end block"))
    end

    metadata_exprs = []
    mixin_exprs = Expr[]

    mixin_idx = 0
    for arg in expr.args
        arg isa LineNumberNode && continue

        has_docs = arg isa Expr && arg.head === :macrocall && arg.args[1] isa GlobalRef

        if has_docs
            docs = arg.args[3]
            attr = arg.args[4]
        else
            docs = nothing
            attr = arg
        end

        is_attr_line = attr isa Expr && attr.head === :(=) && length(attr.args) == 2
        is_mixin_line = attr isa Expr && attr.head === :(...) && length(attr.args) == 1
        if !(is_attr_line || is_mixin_line)
            error("Failed to parse Attributes: \"$attr\" is neither a valid attribute line like `x = default_value` nor a mixin line like `some_mixin...`")
        end

        if is_attr_line
            if MacroTools.@capture(attr, sym_::type_ = default_)
                # capture spawns all variables we need
            elseif MacroTools.@capture(attr, sym_ = default_)
                type = :Any
            else
                error("Could not parse attribute expr $expr")
            end
            if !(sym isa Symbol)
                error("$sym should be a symbol")
            end
            qsym = QuoteNode(sym)
            metadata = quote
                default_value = $(get_default_expr(default, (attribute_path..., sym)))
                am = Makie.AttributeMetadata(;
                    docstring = $docs,
                    default_value = default_value,
                    default_expr = $(default_expr_string(default)),
                    type = $type
                )
                Makie.set_metadata!(d, $qsym, am)
            end
            push!(metadata_exprs, metadata)
        elseif is_mixin_line
            mixin_idx += 1
            mixin = only(attr.args)
            push!(
                mixin_exprs, quote
                    mixins[$mixin_idx] = $(esc(mixin))
                    if !(mixins[$mixin_idx] isa DocumentedAttributes)
                        error("Mixin was not a DocumentedAttributes but $(mixins[$mixin_idx])")
                    end
                end
            )

            # docstrings and default expressions of the mixed in
            # DocumentedAttributes are inserted
            metadata_exp = quote
                for (key, value) in mixins[$mixin_idx]
                    if haskey(d, key)
                        error("Mixin `$($(QuoteNode(mixin)))` had the key :$key which already existed. It's not allowed for mixins to overwrite keys to avoid accidental overwrites. Drop those keys from the mixin first.")
                    end
                    d[key] = value
                end
            end
            push!(metadata_exprs, metadata_exp)
        else
            error("Unreachable")
        end
    end

    # Both `let` and `local` are need to prevent nested attributes from writing
    # to the same DocumentedAttributes (which can create recursive references)
    return quote
        let
            mixins = Dict{Int, Makie.DocumentedAttributes}()
            $(mixin_exprs...)
            local d = Dict{Symbol, Makie.AttributeMetadata}()
            $(metadata_exprs...)
            Makie.DocumentedAttributes(d)
        end
    end
end

# This is only meant for compat with old style recipes
function convert_old_attributes_expr(func_expr)
    # remove the function header and just work on the body
    ex = func_expr.args[2]

    # preserve :fonts
    expr = MacroTools.prewalk(ex) do x
        if MacroTools.@capture(x, key_ = Attributes(args__))
            if key === :fonts
                return :($key = Dict($args))
            else
                return x
            end
        else
            return x
        end
    end

    # Process old syntax to DocumentedAttributes syntax
    expr = MacroTools.postwalk(expr) do x
        if MacroTools.@capture(x, theme(scene_, key_))
            return :(Makie.Inherit(($key,)))
        elseif MacroTools.@capture(x, lift(f_, Makie.Inherit(key_tuple_)))
            return :(Makie.Inherit($f, $key_tuple))
        elseif MacroTools.@capture(x, map(f_, Makie.Inherit(key_tuple_)))
            return :(Makie.Inherit($f, $key_tuple))
        elseif MacroTools.@capture(x, Attributes(args__))
            dict_call = :(Makie.DocumentedAttributes())
            for arg in args
                # Need to be careful to not match normal Code with this, e.g.
                # value = sin(1) # don't make this value => AttributeMetadata(nothing, sin(1), "sin(1)")
                # ...
                # return Attributes(a = value) # only here
                if MacroTools.@capture(arg, key_ = val_)
                    str = Makie.default_expr_string(val)
                    element_expr = :($(QuoteNode(key)) => Makie.AttributeMetadata(nothing, $val, $str, Any))
                    push!(dict_call.args, element_expr)
                else
                    error("Failed to match $arg")
                end
            end
            return dict_call
        elseif MacroTools.@capture(x, return arg_)
            return :($arg)
        end
        return x
    end

    # revert :fonts to Attributes
    expr = MacroTools.prewalk(expr) do x
        if MacroTools.@capture(x, key_ = Dict(args__))
            if key === :fonts
                return :($key = Attributes($args))
            else
                return x
            end
        else
            return x
        end
    end

    # let to not allow any enclosed variables to spill out
    return :(let; $expr end)
end

################################################################################
### Utilities
################################################################################

Base.copy(d::DocumentedAttributes) = DocumentedAttributes(copy(d.d))
Base.pop!(d::DocumentedAttributes, key::Symbol) = pop!(d.d, key)
Base.getindex(d::DocumentedAttributes, key::Symbol) = d.d[key]
Base.get(d::DocumentedAttributes, key::Symbol, default) = get(d.d, key, default)
Base.keys(d::DocumentedAttributes) = keys(d.d)
Base.iterate(d::DocumentedAttributes) = iterate(d.d)
Base.iterate(d::DocumentedAttributes, state) = iterate(d.d, state)
Base.length(d::DocumentedAttributes) = length(d.d)
Base.haskey(d::DocumentedAttributes, key::Symbol) = haskey(d.d, key)
Base.filter!(f, d::DocumentedAttributes) = filter!(f, d.d)

is_nested(a::AttributeMetadata) = a.default_value isa DocumentedAttributes

# for testing
function Base.:(==)(a::DocumentedAttributes, b::DocumentedAttributes)
    issetequal(keys(a), keys(b)) || return false
    for key in keys(a)
        x = a[key] == b[key]
        x || return false
    end
    return true
end
function Base.:(==)(a::AttributeMetadata, b::AttributeMetadata)
    return (a.docstring == b.docstring) &&
        (a.default_expr == b.default_expr) &&
        (a.type == b.type) &&
        (a.default_value == b.default_value)
end
function Base.:(==)(a::Inherit, b::Inherit)
    return (a.keys == b.keys) && (a.callback == b.callback) && (a.fallback == b.fallback)
end

function Base.show(io::IO, a::DocumentedAttributes)
    return print_documented_attributes(io, a, 1)
end

function print_documented_attributes(io, a::DocumentedAttributes, tab)
    maxlength = 100
    print(io, "DocumentedAttributes(")
    for (k, v) in a
        if !isnothing(v.docstring)
            docs = if length(v.docstring) > maxlength
                v.docstring[1:maxlength] * "..."
            else
                v.docstring
            end
            print(io, "\n", "   "^tab, '"', docs, '"')
        end
        Tstr = v.type === Any ? "" : "::$(v.type)"
        print(io, "\n", "   "^tab, k, Tstr, " = ")
        print_documented_attributes(io, v, tab)
    end
    print(io, "\n", "   "^(tab-1), ")")
    return io
end

function print_documented_attributes(io, m::AttributeMetadata, tab)
    if m.default_value isa DocumentedAttributes
        print_documented_attributes(io, m.default_value, tab+1)
    else
        print(io, m.default_expr)
    end
end

"""
    filtered_attributes(Type[; allow, exclude])

Filters the top level attributes returned by `documented_attributes(Type)`.
If `allow` is given, only the attribute with names in `allow` are kept.
If `exclude` is given, all attribute names in `exclude` are removed.

This creates a copy of the documented attributes, i.e. won't modify them directly.
"""
filtered_attributes(T; kwargs...) = filter_attributes(documented_attributes(T); kwargs...)

"""
    filtered_attributes(attributes[; allow, exclude])

Creates a filtered copy of the given `attributes`.
If `allow` is given, only the attribute with names in `allow` are kept.
If `exclude` is given, all attribute names in `exclude` are removed.

Note that this only acts on top level attributes.
"""
function filter_attributes(attr; kwargs...)
    return filter_attributes!(copy(attr); kwargs...)
end

function filter_attributes!(attr; allow = tuple(), exclude = tuple())
    !isempty(allow) && filter!(p -> p[1] in allow, attr)
    !isempty(exclude) && filter!(p -> !(p[1] in exclude), attr)
    return attr
end

function error_on_no_fallback(keys, val)
    if val === NoFallback()
        s = join(keys, '.')
        error("Current theme does not include a default for $s and the attribute does not provide a fallback.")
    end
    return
end

function error_on_no_fallback(type, keys, val)
    if val === NoFallback()
        s = join(keys, '.')
        error("Current theme does not include a default for $type.$s and the attribute does not provide a fallback.")
    end
    return
end

function set_nested!(a::Attributes, value, key::Symbol, keys::Symbol...)
    return set_nested!(get!(a, key, Attributes()), value, keys...)
end
set_nested!(a::Attributes, value, key::Symbol) = a[key] = value

# This is more complete than before, also including overwrites from theme[Plot/Block]
# and trying global themes before using fallbacks
"""
    default_theme(scene, type)

Returns the default attributes of plot or block `type` while considering the
theme of the given scene. If the `scene = nothing`, only defaults from the
global theme are used.

For the raw theme of a plot or block type, see `Makie.documented_attributes(type)`.
For looking up a specific value, see `Makie.lookup_default(type, scene, keys...)`.
For updating another data structure, see `Makie.apply_attribute_defaults!(callback, type, scene)`.
"""
function default_theme(scene, T::Type)
    output = Attributes()
    apply_attribute_defaults!(T, scene) do keys, type, value
        set_nested!(output, value, keys...)
    end
    return output
end

################################################################################
### Attribute Defaulting
################################################################################

"""
    apply_attribute_defaults!(callback, type, scene[; kwargs...])

Recursively traverses the `documented_attributes(type)` and calls
`callback(keys, attribute_type, attribute_value)` for each leaf attribute. Any
themes needed to derive attribute values are pulled from `theme(scene)`.

## Callback

- `keys` are a tuple of symbols corresponding to the keys leading to the leaf
    attribute. They always include at least one symbol (unnested case).
- `attribute_type` is the type annotation given to the attribute in the documented
    attributes. This defaults to `Any` if no types are given and is generally only
    used for blocks.
- `attribute_value` is the value returned by `lookup_default_typed`, i.e. the
    fully resolved value of the attribute after inheriting from the themes as well
    as the optionally given `kwdict`.

Note that `attribute_value` may be a `NoFallback()`. To error check this
`Makie.error_on_no_fallback(keys, x)` can be used.

## Keyword Arguments

- `kwdict` is the highest priority "theme" from which overwrites any other
    defaults set for an attribute. In practice the `kwdict` is usually the
    keyword arguments passed to a plot or block constructor.
- `delete_used_kwargs = false` removes any used attributes from `kwdict`. Used
    for validation in blocks.
- `exclude` is an optional set of excluded keys. It currently only applies to
    top level attributes.
"""
function apply_attribute_defaults!(
        f, type::Type, scene;
        kwdict = NamedTuple(), delete_used_kwargs = false, exclude = tuple()
    )
    name = type <: Block ? nameof(type) : plotsym(type)

    doc_attr = documented_attributes(type)
    default_theme = theme(scene)
    global_overwrite_theme = theme(name, default = NamedTuple())
    overwrite_theme = get(theme(scene), name, NamedTuple())

    return apply_attribute_defaults!(
        f, tuple(),
        doc_attr, default_theme, global_overwrite_theme, overwrite_theme, kwdict;
        delete_used_kwargs, exclude
    )
end

"""
    apply_attribute_defaults!(callback, documented_attributes[; kwargs...]),)

Alternative call signature with directly passed `documented_attributes`. Themes
are included with additional, optional keyword arguments:

- `overwrite_theme`: The `theme(scene)[name]` of the parent scene where `name`
    is the plot or blocks name. This acts as an overwrite for attributes derived
    from `documented_attributes` (including `@inherit`)
- `global_overwrite_theme`: The `theme(nothing)[name]` where `name` is the plot or
    block name. This acts as an overwrite for attribute defaults if
    `overwrite_theme` does not contain the current attribute name.
- `default_theme`: The parent scenes `theme(scene)`, used for resolving `@inherit`
"""
function apply_attribute_defaults!(
        f, doc_attr;
        delete_used_kwargs = false,
        exclude = tuple(),
        default_theme = NamedTuple(),
        global_overwrite_theme = NamedTuple(),
        overwrite_theme = NamedTuple(),
        kwdict = NamedTuple()
    )
    return apply_attribute_defaults!(
        f, tuple(),
        doc_attr, default_theme, global_overwrite_theme, overwrite_theme, kwdict;
        delete_used_kwargs, exclude
    )
end

function apply_attribute_defaults!(
        f, trace, doc_attr, theme, gtheme, otheme, kwdict;
        delete_used_kwargs = false, exclude = tuple()
    )
    return apply_attribute_defaults!(
        f, trace, exclude, delete_used_kwargs,
        doc_attr, theme, gtheme, otheme, kwdict
    )
end

function apply_attribute_defaults!(
        f, _trace, exclude, delete_kw, doc_attr,
        default_theme, global_overwrite_theme, overwrite_theme, user_attributes
    )
    for (key, meta) in doc_attr
        key in exclude && continue
        trace = (_trace..., key)

        if is_nested(meta)
            apply_attribute_defaults!(
                f, trace, tuple(), delete_kw,
                meta.default_value,
                default_theme,
                get(global_overwrite_theme, key, NamedTuple()),
                get(overwrite_theme, key, NamedTuple()),
                get(user_attributes, key, NamedTuple())
            )
            if delete_kw
                if haskey(user_attributes, key) && isempty(user_attributes[key])
                    pop!(user_attributes, key)
                end
            end
        else
            T, default = lookup_default_typed(
                doc_attr, default_theme, global_overwrite_theme, overwrite_theme,
                user_attributes, trace, delete_kw, key
            )
            f(trace, T, default)
        end
    end
end

function lookup_default_typed(
        doc_attr::DocumentedAttributes,
        default_theme, global_overwrite_theme, overwrite_theme, user_attributes,
        trace::Tuple, delete_kw::Bool, key::Symbol
    )
    # If this is called from apply_attribute_defaults!() the attribute is
    # guaranteed to exist. If we call this from lookup_default(_typed) it may not.
    meta = get(doc_attr, key, AttributeMetadata(nothing, Inherit(trace, NoFallback()), "", Any))
    T = meta.type
    default = meta.default_value

    if is_nested(meta)
        s = join(trace, '.')
        error("$s is not a leaf Attribute")
    end

    theme_default = _lookup_default_from_themes(
        default, default_theme, global_overwrite_theme, overwrite_theme, key
    )

    if haskey(user_attributes, key)
        # Note: merging a Dict-like theme_default with dict-like kw hurts runtime
        # performance here (with dispatch and with isa checks)
        kw = delete_kw ? pop!(user_attributes, key) : user_attributes[key]
        return T, kw
    else

        return T, theme_default
    end
end

# Note: @nospecialize() helps runtime performance quite a bit here
function _lookup_default_from_themes(
        @nospecialize(default), default_theme, global_overwrite_theme, overwrite_theme, key
    )
    # These to_value() calls are important for `add_theme!(plot)`
    if haskey(overwrite_theme, key)
        return to_value(overwrite_theme[key])
    elseif haskey(global_overwrite_theme, key)
        return to_value(global_overwrite_theme[key])
    elseif default isa Inherit
        return inherit_default(default, default_theme)
    else
        return default
    end
end

"""
    inherit_default(inherit::Inherit, scene_theme)

Resolves an inherited attribute by inheriting it from `scene_theme` or the global
`theme(nothing)` as a backup. `inherit.callback` is applied to the result before
returning.

This function may act recursively if `fallback` is another `Inherit`. If no
default could be inherited and the function will return `inherit.fallback` even
if it is `NoFallback()`. (No error checking here)
"""
function inherit_default(inherit::Inherit, scene_theme)
    result = inherit_default(scene_theme, inherit.fallback, inherit.keys...)
    if result isa Inherit # nested inherit
        return inherit_default(result, scene_theme)
    end
    return inherit.callback(to_value(result))
end

function inherit_default(theme, fallback, key::Symbol, keys::Symbol...)
    return haskey(theme, key) ? inherit_default(theme[key], fallback, keys...) : fallback
end
inherit_default(theme, fallback, key::Symbol) = get(theme, key, fallback)


################################################################################
### Attribute Defaulting for single attributes
################################################################################


"""
    lookup_default(type, scene, keys...[; kwargs...])

Looks up the default value of a single attribute identified by `keys`
for the given plot or block `type` with the themes defined in `scene`. Multiple
keys are used to refer to nested attributes.

## Keyword Arguments

- `kwdict` is the highest priority "theme" from which overwrites any other
    defaults set for an attribute. In practice the `kwdict` is usually the
    keyword arguments passed to a plot or block constructor.
- `delete_used_kwargs = false` removes any used attributes from `kwdict`. Used
    for validation in blocks.

Note that this function does not error if `NoFallback()` is the return. (I.e if
no valid default was found)

---

    lookup_default(documented_attributes, keys...[; kwargs...]),)

Alternative call signature with directly passed `documented_attributes`. Themes
are included with additional, optional keyword arguments:

- `overwrite_theme`: The `theme(scene)[name]` of the parent scene where `name`
    is the plot or blocks name. This acts as an overwrite for attributes derived
    from `documented_attributes` (including `@inherit`)
- `global_overwrite_theme`: The `theme(nothing)[name]` where `name` is the plot or
    block name. This acts as an overwrite for attribute defaults if
    `overwrite_theme` does not contain the current attribute name.
- `default_theme`: The parent scenes `theme(scene)`, used for resolving `@inherit`
"""
function lookup_default(args...; kwargs...)
    T, val = lookup_default_typed(args...; kwargs...)
    return val
end

"""
    lookup_default_typed(type, scene, keys...[; kwargs...])

Looks up the default value and type of a single attribute identified by (nested)
`keys`. The lookup follows the same prioritization scheme as plot/block attributes,
but does not require `keys` to exist as a plot/block attribute.


## Keyword Arguments

- `kwdict` is the highest priority "theme" from which overwrites any other
    defaults set for an attribute. In practice the `kwdict` is usually the
    keyword arguments passed to a plot or block constructor.
- `delete_used_kwargs = false` removes any used attributes from `kwdict`. Used
    for validation in blocks.

Note that this function does not error if `NoFallback()` is the return. (I.e if
no valid default was found)
"""
function lookup_default_typed(
        ::Type{T}, scene, keys::Symbol...;
        kwdict = NamedTuple(), delete_used_kwargs = false
    ) where {T}
    name = T isa Block ? nameof(type) : plotsym(T)
    return lookup_default_typed(
        documented_attributes(T),
        theme(scene),
        get(theme(nothing), name, NamedTuple()),
        get(theme(scene), name, NamedTuple()),
        kwdict, delete_used_kwargs, keys...
    )
end

"""
    lookup_default_typed(documented_attributes, keys...[; kwargs...]),)

Alternative call signature with directly passed `documented_attributes`. Themes
are included with additional, optional keyword arguments:

- `overwrite_theme`: The `theme(scene)[name]` of the parent scene where `name`
    is the plot or blocks name. This acts as an overwrite for attributes derived
    from `documented_attributes` (including `@inherit`)
- `global_overwrite_theme`: The `theme(nothing)[name]` where `name` is the plot or
    block name. This acts as an overwrite for attribute defaults if
    `overwrite_theme` does not contain the current attribute name.
- `default_theme`: The parent scenes `theme(scene)`, used for resolving `@inherit`
"""
function lookup_default_typed(
        doc_attr, keys::Symbol...;
        default_theme = NamedTuple(),
        global_overwrite_theme = NamedTuple(),
        overwrite_theme = NamedTuple(),
        kwdict = NamedTuple(), delete_used_kwargs = false
    )
    return lookup_default_typed(
        doc_attr, default_theme, global_overwrite_theme, overwrite_theme, kwdict,
        delete_used_kwargs, keys...
    )
end

function lookup_default_typed(
        block_defaults::DocumentedAttributes,
        default_theme, global_overwrite_theme, overwrite_theme, user_attributes,
        delete_kw::Bool, keys::Symbol...
    )
    lookup_default_typed(
        block_defaults, default_theme, global_overwrite_theme, overwrite_theme,
        user_attributes, keys, delete_kw, keys...
    )
end

function lookup_default_typed(
        block_defaults::DocumentedAttributes,
        default_theme, global_overwrite_theme, overwrite_theme, user_attributes,
        keys::Symbol...
    )
    lookup_default_typed(
        block_defaults, default_theme, global_overwrite_theme, overwrite_theme,
        user_attributes, keys, false, keys...
    )
end

function lookup_default_typed(
        block_defaults::DocumentedAttributes,
        default_theme, global_overwrite_theme, overwrite_theme, user_attributes,
        trace::Tuple, delete_kw::Bool, key::Symbol, keys::Symbol...
    )
    lookup_default_typed(
        get(block_defaults, key, NamedTuple()),
        default_theme,
        get(global_overwrite_theme, key, NamedTuple()),
        get(overwrite_theme, key, NamedTuple()),
        get(user_attributes, key, NamedTuple()),
        trace, delete_kw, keys...
    )
end

################################################################################
### Compat / Deprecations
################################################################################
