name = "MakieRecipes"
uuid = "3c562d8e-4afa-4f1c-99bf-ad54af2b207f"
authors = ["Simon Danisch", "Anshul Singhvi <anshulsinghvi@gmail.com>"]
version = "0.1.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
RecipesPipeline = "01d81517-befc-4cb6-b9ec-a95719d0359c"

[compat]
Colors = "0.9, 0.10, 0.11, 0.12"
RecipesBase = "1"
RecipesPipeline = "0.1"
julia = "1.5"
