image: julia:1.5

before_script:
  - apt-get -qq update; apt-get -y install git python3-dev python3-pip
  - pip3 install css-html-js-minify
    
pages:
  stage: deploy
  script:
    - julia --project=@. -e 'import Pkg; Pkg.instantiate();
      using NodeJS; run(`$(npm_cmd()) install highlight.js`);
      using Franklin;
      optimize()'
    - mv __site public
  artifacts:
    paths:
      - public
  only:
    - master

