function theme_black()
    return Theme(
        backgroundcolor = :black,
        textcolor = :white,
        linecolor = :white,
        palette = generate_default_palette(:black),
        Axis = (
            backgroundcolor = :transparent,
            bottomspinecolor = :white,
            topspinecolor = :white,
            leftspinecolor = :white,
            rightspinecolor = :white,
            xgridcolor = RGBAf(1, 1, 1, 0.16),
            ygridcolor = RGBAf(1, 1, 1, 0.16),
            xtickcolor = :white,
            ytickcolor = :white,
        ),
        Legend = (
            framecolor = :white,
            backgroundcolor = :black,
        ),
        Axis3 = (
            xgridcolor = RGBAf(1, 1, 1, 0.16),
            ygridcolor = RGBAf(1, 1, 1, 0.16),
            zgridcolor = RGBAf(1, 1, 1, 0.16),
            xspinecolor_1 = :white,
            yspinecolor_1 = :white,
            zspinecolor_1 = :white,
            xspinecolor_2 = :white,
            yspinecolor_2 = :white,
            zspinecolor_2 = :white,
            xspinecolor_3 = :white,
            yspinecolor_3 = :white,
            zspinecolor_3 = :white,
            xspinecolor_4 = :white,
            yspinecolor_4 = :white,
            zspinecolor_4 = :white,
            xticklabelpad = 3,
            yticklabelpad = 3,
            zticklabelpad = 6,
            xtickcolor = :white,
            ytickcolor = :white,
            ztickcolor = :white,
        ),
        Colorbar = (
            tickcolor = :white,
            spinecolor = :white,
            topspinecolor = :white,
            bottomspinecolor = :white,
            leftspinecolor = :white,
            rightspinecolor = :white,
        )
    )
end
