name: Codespell
on:
  workflow_call:

jobs:
  check:
    name: Codespell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: codespell-project/actions-codespell@v2
        with:
          ignore_words_list: indexin,doubleclick,Heros,OT,jus,bu,te,lins,Missings
          skip: '*.js,*.vert,*.ai,*.frag,*.geom'
          only_warn: 1
