name: CompatHelper
on:
  schedule:
    - cron: '0 0 * * *'  # Everyday at midnight
  workflow_dispatch:
jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Pkg.add("CompatHelper")
        run: julia -e 'using Pkg; Pkg.add("CompatHelper")'
      - name: CompatHelper.main()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.DOCUMENTER_KEY }}
        run: julia -e 'using CompatHelper; CompatHelper.main()'
